// Compliance Engine
// Auto labor law monitoring, handbook builder, violation detection, EEO reporting

import { db, schema } from '@/lib/db'
import { eq, and } from 'drizzle-orm'

// ---------------------------------------------------------------------------
// Labor Law Database (built-in rules per jurisdiction)
// ---------------------------------------------------------------------------

export interface LaborLawRule {
  id: string
  jurisdiction: string // e.g., "US-CA", "US-NY", "UK", "DE"
  category: 'minimum_wage' | 'overtime' | 'breaks' | 'leave' | 'termination' | 'benefits' | 'discrimination' | 'safety'
  title: string
  description: string
  requirement: string
  effectiveDate: string
  source: string
  severity: 'info' | 'warning' | 'critical'
}

export interface ComplianceViolation {
  id: string
  ruleId: string
  employeeId?: string
  severity: 'info' | 'warning' | 'critical'
  title: string
  description: string
  remediation: string
  detectedAt: string
  resolvedAt?: string
}

export interface HandbookSection {
  id: string
  title: string
  category: string
  content: string
  jurisdiction: string
  lastUpdated: string
  autoGenerated: boolean
}

// Built-in labor law rules database
const LABOR_LAW_RULES: LaborLawRule[] = [
  // US Federal
  { id: 'us-fed-min-wage', jurisdiction: 'US', category: 'minimum_wage', title: 'Federal Minimum Wage', description: 'Federal minimum wage under FLSA', requirement: 'Minimum $7.25/hour for non-exempt employees', effectiveDate: '2009-07-24', source: 'Fair Labor Standards Act (FLSA)', severity: 'critical' },
  { id: 'us-fed-overtime', jurisdiction: 'US', category: 'overtime', title: 'Overtime Pay', description: 'FLSA overtime requirements', requirement: '1.5x regular rate for hours worked over 40 in a workweek', effectiveDate: '1938-06-25', source: 'FLSA §207', severity: 'critical' },
  { id: 'us-fed-fmla', jurisdiction: 'US', category: 'leave', title: 'Family and Medical Leave', description: 'FMLA leave requirements', requirement: 'Up to 12 weeks unpaid leave for qualifying events (50+ employees)', effectiveDate: '1993-08-05', source: 'Family and Medical Leave Act', severity: 'critical' },
  { id: 'us-fed-ada', jurisdiction: 'US', category: 'discrimination', title: 'Disability Accommodation', description: 'ADA reasonable accommodation', requirement: 'Reasonable accommodations for qualified individuals with disabilities', effectiveDate: '1990-07-26', source: 'Americans with Disabilities Act', severity: 'critical' },
  { id: 'us-fed-eeo', jurisdiction: 'US', category: 'discrimination', title: 'Equal Employment Opportunity', description: 'Title VII anti-discrimination', requirement: 'No discrimination based on race, color, religion, sex, or national origin', effectiveDate: '1964-07-02', source: 'Title VII, Civil Rights Act', severity: 'critical' },
  { id: 'us-fed-osha', jurisdiction: 'US', category: 'safety', title: 'Workplace Safety', description: 'OSHA general duty clause', requirement: 'Provide workplace free from recognized hazards', effectiveDate: '1970-12-29', source: 'Occupational Safety and Health Act', severity: 'critical' },

  // US California
  { id: 'us-ca-min-wage', jurisdiction: 'US-CA', category: 'minimum_wage', title: 'California Minimum Wage', description: 'CA minimum wage (26+ employees)', requirement: 'Minimum $16.50/hour (2026)', effectiveDate: '2026-01-01', source: 'CA Labor Code §1182.12', severity: 'critical' },
  { id: 'us-ca-meal-break', jurisdiction: 'US-CA', category: 'breaks', title: 'Meal Break Requirements', description: 'CA meal break law', requirement: '30-min unpaid meal break before 5th hour; 2nd break before 10th hour', effectiveDate: '2000-01-01', source: 'CA Labor Code §512', severity: 'critical' },
  { id: 'us-ca-rest-break', jurisdiction: 'US-CA', category: 'breaks', title: 'Rest Break Requirements', description: 'CA rest period', requirement: '10-min paid rest break per 4 hours worked', effectiveDate: '2000-01-01', source: 'CA IWC Orders', severity: 'warning' },
  { id: 'us-ca-sick-leave', jurisdiction: 'US-CA', category: 'leave', title: 'Paid Sick Leave', description: 'CA paid sick leave', requirement: 'Minimum 5 days (40 hours) paid sick leave per year', effectiveDate: '2024-01-01', source: 'CA Labor Code §245-249', severity: 'critical' },
  { id: 'us-ca-pay-transparency', jurisdiction: 'US-CA', category: 'benefits', title: 'Pay Transparency', description: 'SB 1162 pay scale disclosure', requirement: 'Include pay scale in job postings; provide to current employees on request', effectiveDate: '2023-01-01', source: 'SB 1162', severity: 'warning' },

  // US New York
  { id: 'us-ny-min-wage', jurisdiction: 'US-NY', category: 'minimum_wage', title: 'New York Minimum Wage', description: 'NY minimum wage', requirement: 'Minimum $16.50/hour (NYC, 2026)', effectiveDate: '2026-01-01', source: 'NY Labor Law §652', severity: 'critical' },
  { id: 'us-ny-paid-leave', jurisdiction: 'US-NY', category: 'leave', title: 'NY Paid Family Leave', description: 'NY PFL', requirement: '12 weeks paid family leave at 67% of average weekly wage', effectiveDate: '2021-01-01', source: 'NY Workers Comp Law Art. 9', severity: 'critical' },

  // UK
  { id: 'uk-min-wage', jurisdiction: 'UK', category: 'minimum_wage', title: 'National Minimum Wage', description: 'UK NMW/NLW', requirement: '£12.21/hour (National Living Wage, 21+, 2026)', effectiveDate: '2026-04-01', source: 'National Minimum Wage Act 1998', severity: 'critical' },
  { id: 'uk-working-time', jurisdiction: 'UK', category: 'overtime', title: 'Working Time Regulations', description: 'Max working hours', requirement: 'Maximum 48 hours per week (averaged over 17 weeks, opt-out available)', effectiveDate: '1998-10-01', source: 'Working Time Regulations 1998', severity: 'warning' },
  { id: 'uk-annual-leave', jurisdiction: 'UK', category: 'leave', title: 'Statutory Annual Leave', description: 'UK statutory holiday', requirement: '28 days paid annual leave (inc. bank holidays) for full-time workers', effectiveDate: '2009-04-01', source: 'Working Time Regulations 1998', severity: 'critical' },

  // Germany
  { id: 'de-min-wage', jurisdiction: 'DE', category: 'minimum_wage', title: 'Mindestlohn', description: 'German minimum wage', requirement: '€12.82/hour (2026)', effectiveDate: '2026-01-01', source: 'Mindestlohngesetz (MiLoG)', severity: 'critical' },
  { id: 'de-annual-leave', jurisdiction: 'DE', category: 'leave', title: 'Bundesurlaubsgesetz', description: 'German statutory leave', requirement: 'Minimum 24 working days paid leave (6-day week) or 20 days (5-day week)', effectiveDate: '1963-01-08', source: 'BUrlG §3', severity: 'critical' },
  { id: 'de-termination', jurisdiction: 'DE', category: 'termination', title: 'Kündigungsschutz', description: 'Termination protection', requirement: 'Minimum 4 weeks notice; protection from unfair dismissal (10+ employees)', effectiveDate: '1951-08-10', source: 'KSchG', severity: 'critical' },

  // France
  { id: 'fr-working-time', jurisdiction: 'FR', category: 'overtime', title: 'Durée du travail', description: 'French 35-hour week', requirement: '35-hour standard work week; overtime above 35h', effectiveDate: '2000-02-01', source: 'Code du travail L3121', severity: 'critical' },
  { id: 'fr-annual-leave', jurisdiction: 'FR', category: 'leave', title: 'Congés payés', description: 'French statutory leave', requirement: '30 working days (5 weeks) paid annual leave', effectiveDate: '1982-01-16', source: 'Code du travail L3141', severity: 'critical' },
]

// ---------------------------------------------------------------------------
// Compliance Scanning
// ---------------------------------------------------------------------------

export function getApplicableRules(countries: string[]): LaborLawRule[] {
  const jurisdictions = new Set<string>()

  for (const country of countries) {
    // Map country names/codes to jurisdiction codes
    const upper = country.toUpperCase()
    if (upper === 'US' || upper === 'USA' || upper === 'UNITED STATES') jurisdictions.add('US')
    if (upper.startsWith('US-') || upper === 'CALIFORNIA') jurisdictions.add('US-CA')
    if (upper === 'US-NY' || upper === 'NEW YORK') jurisdictions.add('US-NY')
    if (upper === 'UK' || upper === 'GB' || upper === 'UNITED KINGDOM') jurisdictions.add('UK')
    if (upper === 'DE' || upper === 'GERMANY') jurisdictions.add('DE')
    if (upper === 'FR' || upper === 'FRANCE') jurisdictions.add('FR')
    // Add US federal for any US state
    if (upper.startsWith('US') || upper === 'USA' || upper === 'UNITED STATES') jurisdictions.add('US')
  }

  return LABOR_LAW_RULES.filter(r => jurisdictions.has(r.jurisdiction))
}

export async function scanCompliance(orgId: string): Promise<{
  violations: ComplianceViolation[]
  applicableRules: LaborLawRule[]
  score: number
  summary: { total: number; critical: number; warnings: number; info: number }
}> {
  // Get all employee countries
  const employees = await db.select({
    id: schema.employees.id,
    country: schema.employees.country,
    jobTitle: schema.employees.jobTitle,
    isActive: schema.employees.isActive,
  }).from(schema.employees).where(eq(schema.employees.orgId, orgId))

  const countries = [...new Set(employees.map(e => e.country).filter(Boolean) as string[])]
  const rules = getApplicableRules(countries)
  const violations: ComplianceViolation[] = []

  // Check for common violations
  // 1. Missing job titles (needed for EEO)
  const missingTitles = employees.filter(e => e.isActive && !e.jobTitle)
  if (missingTitles.length > 0) {
    violations.push({
      id: `v-missing-titles-${orgId}`,
      ruleId: 'us-fed-eeo',
      severity: 'warning',
      title: 'Missing Job Titles',
      description: `${missingTitles.length} active employees lack job titles, required for EEO reporting.`,
      remediation: 'Update employee records to include job titles via People > Edit Employee.',
      detectedAt: new Date().toISOString(),
    })
  }

  // 2. Check leave request compliance
  const leaveRequests = await db.select().from(schema.leaveRequests)
    .where(eq(schema.leaveRequests.orgId, orgId))
  const rejectedLeave = leaveRequests.filter(l => l.status === 'rejected')
  if (rejectedLeave.length > leaveRequests.length * 0.3 && leaveRequests.length > 5) {
    violations.push({
      id: `v-leave-rejection-rate-${orgId}`,
      ruleId: 'us-fed-fmla',
      severity: 'warning',
      title: 'High Leave Rejection Rate',
      description: `${Math.round((rejectedLeave.length / leaveRequests.length) * 100)}% of leave requests rejected. Review for FMLA compliance.`,
      remediation: 'Audit rejected leave requests to ensure no protected leave was improperly denied.',
      detectedAt: new Date().toISOString(),
    })
  }

  // 3. Check for pay equity issues
  const salaryReviews = await db.select().from(schema.salaryReviews)
    .where(eq(schema.salaryReviews.orgId, orgId))
  const pendingSalary = salaryReviews.filter(s => s.status === 'pending_approval')
  if (pendingSalary.length > 10) {
    violations.push({
      id: `v-pending-comp-${orgId}`,
      ruleId: 'us-ca-pay-transparency',
      severity: 'info',
      title: 'Pending Compensation Reviews',
      description: `${pendingSalary.length} salary reviews awaiting approval. Delays may impact pay equity compliance.`,
      remediation: 'Process pending salary reviews in Compensation module.',
      detectedAt: new Date().toISOString(),
    })
  }

  const critical = violations.filter(v => v.severity === 'critical').length
  const warnings = violations.filter(v => v.severity === 'warning').length
  const info = violations.filter(v => v.severity === 'info').length
  const score = Math.max(0, 100 - (critical * 20) - (warnings * 5) - (info * 1))

  return {
    violations,
    applicableRules: rules,
    score,
    summary: { total: violations.length, critical, warnings, info },
  }
}

// ---------------------------------------------------------------------------
// Handbook Builder
// ---------------------------------------------------------------------------

export function generateHandbook(countries: string[], orgName: string): HandbookSection[] {
  const rules = getApplicableRules(countries)
  const sections: HandbookSection[] = []

  // Welcome section
  sections.push({
    id: 'handbook-welcome',
    title: 'Welcome',
    category: 'general',
    content: `Welcome to ${orgName}. This employee handbook outlines our policies, procedures, and expectations. It is designed to help you understand your rights, responsibilities, and the resources available to you. This handbook is for informational purposes and does not constitute an employment contract.`,
    jurisdiction: 'global',
    lastUpdated: new Date().toISOString(),
    autoGenerated: true,
  })

  // Equal Employment section
  sections.push({
    id: 'handbook-eeo',
    title: 'Equal Employment Opportunity',
    category: 'compliance',
    content: `${orgName} is an equal opportunity employer. We do not discriminate based on race, color, religion, sex, sexual orientation, gender identity, national origin, age, disability, genetic information, veteran status, or any other protected class. We are committed to providing a workplace free from harassment and discrimination.`,
    jurisdiction: 'global',
    lastUpdated: new Date().toISOString(),
    autoGenerated: true,
  })

  // Generate jurisdiction-specific sections
  const categories = [...new Set(rules.map(r => r.category))]
  const categoryTitles: Record<string, string> = {
    minimum_wage: 'Compensation',
    overtime: 'Working Hours & Overtime',
    breaks: 'Meal & Rest Breaks',
    leave: 'Leave & Time Off',
    termination: 'Separation & Termination',
    benefits: 'Benefits & Pay Transparency',
    discrimination: 'Anti-Discrimination & Harassment',
    safety: 'Workplace Safety',
  }

  for (const category of categories) {
    const categoryRules = rules.filter(r => r.category === category)
    const jurisdictions = [...new Set(categoryRules.map(r => r.jurisdiction))]

    let content = ''
    for (const jurisdiction of jurisdictions) {
      const jRules = categoryRules.filter(r => r.jurisdiction === jurisdiction)
      content += `**${jurisdiction}:**\n`
      for (const rule of jRules) {
        content += `- ${rule.title}: ${rule.requirement}\n`
      }
      content += '\n'
    }

    sections.push({
      id: `handbook-${category}`,
      title: categoryTitles[category] || category,
      category: 'compliance',
      content: content.trim(),
      jurisdiction: jurisdictions.join(', '),
      lastUpdated: new Date().toISOString(),
      autoGenerated: true,
    })
  }

  // Code of Conduct
  sections.push({
    id: 'handbook-conduct',
    title: 'Code of Conduct',
    category: 'general',
    content: `All employees of ${orgName} are expected to conduct themselves professionally, treat colleagues with respect, protect confidential information, avoid conflicts of interest, and comply with all applicable laws and company policies. Violations may result in disciplinary action up to and including termination.`,
    jurisdiction: 'global',
    lastUpdated: new Date().toISOString(),
    autoGenerated: true,
  })

  return sections
}

// ---------------------------------------------------------------------------
// EEO Reporting
// ---------------------------------------------------------------------------

export interface EEOReport {
  reportDate: string
  orgId: string
  totalEmployees: number
  categories: Array<{
    category: string
    count: number
    percentage: number
  }>
  jobCategories: Array<{
    title: string
    count: number
  }>
  departmentBreakdown: Array<{
    department: string
    count: number
  }>
}

export async function generateEEOReport(orgId: string): Promise<EEOReport> {
  const employees = await db.select().from(schema.employees)
    .where(and(eq(schema.employees.orgId, orgId), eq(schema.employees.isActive, true)))
  const departments = await db.select().from(schema.departments)
    .where(eq(schema.departments.orgId, orgId))

  const deptMap = new Map(departments.map(d => [d.id, d.name]))

  // Job category counts
  const jobCounts = new Map<string, number>()
  const deptCounts = new Map<string, number>()

  for (const emp of employees) {
    const title = emp.jobTitle || 'Unspecified'
    jobCounts.set(title, (jobCounts.get(title) || 0) + 1)
    const dept = emp.departmentId ? deptMap.get(emp.departmentId) || 'Unassigned' : 'Unassigned'
    deptCounts.set(dept, (deptCounts.get(dept) || 0) + 1)
  }

  // Role distribution
  const roleCounts = new Map<string, number>()
  for (const emp of employees) {
    roleCounts.set(emp.role, (roleCounts.get(emp.role) || 0) + 1)
  }

  return {
    reportDate: new Date().toISOString(),
    orgId,
    totalEmployees: employees.length,
    categories: Array.from(roleCounts.entries()).map(([category, count]) => ({
      category,
      count,
      percentage: Math.round((count / employees.length) * 100),
    })),
    jobCategories: Array.from(jobCounts.entries())
      .sort((a, b) => b[1] - a[1])
      .slice(0, 20)
      .map(([title, count]) => ({ title, count })),
    departmentBreakdown: Array.from(deptCounts.entries())
      .sort((a, b) => b[1] - a[1])
      .map(([department, count]) => ({ department, count })),
  }
}
