/**
 * Export / Import Utilities
 *
 * Client-safe functions for exporting data to CSV/JSON/Excel and parsing CSV imports.
 * No database imports -- safe for 'use client' pages.
 */

import * as XLSX from 'xlsx'

// ============================================================
// CSV EXPORT
// ============================================================

interface ExportColumn<T> {
  header: string
  accessor: (row: T) => string | number | boolean | null | undefined
}

/**
 * Export an array of objects to CSV and trigger a browser download.
 */
export function exportToCSV<T>(
  data: T[],
  columns: ExportColumn<T>[],
  filename: string
): void {
  if (data.length === 0) return

  const headers = columns.map(c => escapeCSVField(c.header))
  const rows = data.map(row =>
    columns.map(col => {
      const val = col.accessor(row)
      return escapeCSVField(val == null ? '' : String(val))
    })
  )

  const csvContent = [headers.join(','), ...rows.map(r => r.join(','))].join('\n')
  downloadFile(csvContent, `${filename}.csv`, 'text/csv;charset=utf-8;')
}

function escapeCSVField(value: string): string {
  if (value.includes(',') || value.includes('"') || value.includes('\n')) {
    return `"${value.replace(/"/g, '""')}"`
  }
  return value
}

// ============================================================
// JSON EXPORT
// ============================================================

/**
 * Export data to JSON and trigger a browser download.
 */
export function exportToJSON<T>(data: T[], filename: string): void {
  const jsonContent = JSON.stringify(data, null, 2)
  downloadFile(jsonContent, `${filename}.json`, 'application/json')
}

// ============================================================
// PDF EXPORT (Basic)
// ============================================================

/**
 * Export a simple table to a printable HTML page (opens print dialog).
 */
export function exportToPrint<T>(
  data: T[],
  columns: ExportColumn<T>[],
  title: string
): void {
  const headerRow = columns.map(c => `<th style="padding:8px 12px;text-align:left;border-bottom:2px solid #333;font-size:12px;font-weight:600;color:#333">${c.header}</th>`).join('')
  const bodyRows = data.map(row => {
    const cells = columns.map(col => {
      const val = col.accessor(row)
      return `<td style="padding:6px 12px;border-bottom:1px solid #eee;font-size:11px;color:#555">${val == null ? '' : String(val)}</td>`
    }).join('')
    return `<tr>${cells}</tr>`
  }).join('')

  const html = `<!DOCTYPE html>
<html><head>
<title>${title} - Tempo Export</title>
<style>body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;padding:20px}table{border-collapse:collapse;width:100%}@media print{.no-print{display:none}}</style>
</head><body>
<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:20px">
  <div>
    <h1 style="margin:0;font-size:18px;color:#111">${title}</h1>
    <p style="margin:4px 0 0;font-size:12px;color:#999">Exported ${new Date().toLocaleDateString()} | ${data.length} records | Tempo Platform</p>
  </div>
  <button class="no-print" onclick="window.print()" style="padding:8px 16px;background:#ea580c;color:#fff;border:none;border-radius:6px;cursor:pointer;font-size:12px">Print / Save as PDF</button>
</div>
<table>
  <thead><tr>${headerRow}</tr></thead>
  <tbody>${bodyRows}</tbody>
</table>
<div style="margin-top:20px;text-align:center">
  <p style="font-size:10px;color:#bbb">Generated by Tempo - Unified Workforce Platform</p>
</div>
</body></html>`

  const printWindow = window.open('', '_blank')
  if (printWindow) {
    printWindow.document.write(html)
    printWindow.document.close()
  }
}

// ============================================================
// CSV IMPORT / PARSING
// ============================================================

export interface ParsedCSV {
  headers: string[]
  rows: Record<string, string>[]
  errors: string[]
  totalRows: number
}

/**
 * Parse a CSV string into structured data.
 */
export function parseCSV(csvText: string): ParsedCSV {
  const errors: string[] = []
  const lines = csvText.split(/\r?\n/).filter(line => line.trim().length > 0)

  if (lines.length === 0) {
    return { headers: [], rows: [], errors: ['Empty CSV file'], totalRows: 0 }
  }

  const headers = parseCSVLine(lines[0]).map(h => h.trim())
  if (headers.length === 0) {
    return { headers: [], rows: [], errors: ['No headers found in CSV'], totalRows: 0 }
  }

  const rows: Record<string, string>[] = []
  for (let i = 1; i < lines.length; i++) {
    const values = parseCSVLine(lines[i])
    if (values.length !== headers.length) {
      errors.push(`Row ${i}: Expected ${headers.length} columns, got ${values.length}`)
      continue
    }
    const row: Record<string, string> = {}
    headers.forEach((header, idx) => {
      row[header] = values[idx]?.trim() || ''
    })
    rows.push(row)
  }

  return { headers, rows, errors, totalRows: lines.length - 1 }
}

function parseCSVLine(line: string): string[] {
  const result: string[] = []
  let current = ''
  let inQuotes = false

  for (let i = 0; i < line.length; i++) {
    const ch = line[i]
    if (inQuotes) {
      if (ch === '"') {
        if (i + 1 < line.length && line[i + 1] === '"') {
          current += '"'
          i++
        } else {
          inQuotes = false
        }
      } else {
        current += ch
      }
    } else {
      if (ch === '"') {
        inQuotes = true
      } else if (ch === ',') {
        result.push(current)
        current = ''
      } else {
        current += ch
      }
    }
  }
  result.push(current)
  return result
}

/**
 * Read a File object as CSV text.
 */
export function readFileAsCSV(file: File): Promise<ParsedCSV> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = (e) => {
      const text = e.target?.result as string
      resolve(parseCSV(text))
    }
    reader.onerror = () => reject(new Error('Failed to read file'))
    reader.readAsText(file)
  })
}

// ============================================================
// EMPLOYEE IMPORT MAPPING
// ============================================================

export interface EmployeeImportRow {
  full_name: string
  email: string
  job_title: string
  department: string
  country: string
  hire_date: string
  phone?: string
  location?: string
  level?: string
  manager_email?: string
  employment_type?: string
  bank_name?: string
  bank_account_number?: string
  bank_account_name?: string
  tax_id_number?: string
  date_of_birth?: string
  emergency_contact_name?: string
  emergency_contact_phone?: string
}

const EMPLOYEE_FIELD_ALIASES: Record<string, string[]> = {
  full_name: ['full_name', 'name', 'employee_name', 'fullname', 'full name'],
  email: ['email', 'email_address', 'work_email', 'employee_email'],
  job_title: ['job_title', 'title', 'position', 'role', 'job title'],
  department: ['department', 'dept', 'team', 'division'],
  country: ['country', 'country_code', 'location_country'],
  hire_date: ['hire_date', 'start_date', 'join_date', 'hire date', 'start date'],
  phone: ['phone', 'phone_number', 'mobile', 'telephone'],
  location: ['location', 'office', 'city', 'work_location'],
  level: ['level', 'job_level', 'grade', 'band', 'seniority'],
  manager_email: ['manager_email', 'manager', 'reports_to', 'manager email'],
  employment_type: ['employment_type', 'employment type', 'emp_type', 'emp type', 'type', 'contract_type', 'contract type'],
  bank_name: ['bank_name', 'bank name', 'bank'],
  bank_account_number: ['bank_account_number', 'bank account number', 'account_number', 'account number', 'acct_number', 'acct number'],
  bank_account_name: ['bank_account_name', 'bank account name', 'account_name', 'account name', 'acct_name', 'acct name'],
  tax_id_number: ['tax_id_number', 'tax id number', 'tax_id', 'tax id', 'tin', 'ssn', 'national_id', 'national id'],
  date_of_birth: ['date_of_birth', 'date of birth', 'dob', 'birthdate', 'birth_date', 'birth date', 'birthday'],
  emergency_contact_name: ['emergency_contact_name', 'emergency contact name', 'emergency_contact', 'emergency contact', 'emergency_name', 'emergency name', 'ice_name', 'ice name'],
  emergency_contact_phone: ['emergency_contact_phone', 'emergency contact phone', 'emergency_phone', 'emergency phone', 'ice_phone', 'ice phone'],
}

/**
 * Map CSV headers to employee fields using fuzzy matching.
 */
export function mapCSVToEmployeeFields(headers: string[]): Record<string, string> {
  const mapping: Record<string, string> = {}
  const lowerHeaders = headers.map(h => h.toLowerCase().trim())

  for (const [field, aliases] of Object.entries(EMPLOYEE_FIELD_ALIASES)) {
    for (const alias of aliases) {
      const idx = lowerHeaders.indexOf(alias.toLowerCase())
      if (idx !== -1) {
        mapping[field] = headers[idx]
        break
      }
    }
  }

  return mapping
}

/**
 * Validate imported employee rows.
 */
export function validateEmployeeImport(
  rows: Record<string, string>[],
  mapping: Record<string, string>
): { valid: EmployeeImportRow[]; errors: { row: number; message: string }[] } {
  const valid: EmployeeImportRow[] = []
  const errors: { row: number; message: string }[] = []

  rows.forEach((row, idx) => {
    const name = row[mapping.full_name]
    const email = row[mapping.email]

    if (!name || name.trim().length === 0) {
      errors.push({ row: idx + 2, message: 'Missing employee name' })
      return
    }
    if (!email || !email.includes('@')) {
      errors.push({ row: idx + 2, message: `Invalid email for ${name}` })
      return
    }

    valid.push({
      full_name: name.trim(),
      email: email.trim().toLowerCase(),
      job_title: row[mapping.job_title]?.trim() || 'Team Member',
      department: row[mapping.department]?.trim() || 'General',
      country: row[mapping.country]?.trim() || 'US',
      hire_date: row[mapping.hire_date]?.trim() || new Date().toISOString().split('T')[0],
      phone: row[mapping.phone]?.trim(),
      location: row[mapping.location]?.trim(),
      level: row[mapping.level]?.trim(),
      manager_email: row[mapping.manager_email]?.trim(),
      employment_type: row[mapping.employment_type]?.trim(),
      bank_name: row[mapping.bank_name]?.trim(),
      bank_account_number: row[mapping.bank_account_number]?.trim(),
      bank_account_name: row[mapping.bank_account_name]?.trim(),
      tax_id_number: row[mapping.tax_id_number]?.trim(),
      date_of_birth: row[mapping.date_of_birth]?.trim(),
      emergency_contact_name: row[mapping.emergency_contact_name]?.trim(),
      emergency_contact_phone: row[mapping.emergency_contact_phone]?.trim(),
    })
  })

  return { valid, errors }
}

// ============================================================
// TEMPLATE DOWNLOAD
// ============================================================

/**
 * Triggers download of the CSV template from /templates/employee-import-template.csv
 */
export function downloadImportTemplate(): void {
  const link = document.createElement('a')
  link.href = '/templates/employee-import-template.csv'
  link.download = 'employee-import-template.csv'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}

// ============================================================
// CREDENTIAL GENERATION FOR BULK IMPORT
// ============================================================

export interface EmployeeCredential {
  full_name: string
  email: string
  username: string
  temporary_password: string
  must_change_password: boolean
}

/**
 * Generate a unique username from employee name and email.
 * Format: firstname.lastname (from email or name), with numeric suffix if duplicates exist.
 */
function generateUsername(fullName: string, email: string, existingUsernames: Set<string>): string {
  // Try email prefix first (most common format)
  const emailPrefix = email.split('@')[0].toLowerCase().replace(/[^a-z0-9._-]/g, '')
  if (emailPrefix && !existingUsernames.has(emailPrefix)) {
    existingUsernames.add(emailPrefix)
    return emailPrefix
  }

  // Fall back to name-based
  const parts = fullName.toLowerCase().trim().split(/\s+/)
  const base = parts.length >= 2
    ? `${parts[0]}.${parts[parts.length - 1]}`.replace(/[^a-z0-9._-]/g, '')
    : parts[0].replace(/[^a-z0-9._-]/g, '')

  let candidate = base
  let counter = 1
  while (existingUsernames.has(candidate)) {
    candidate = `${base}${counter}`
    counter++
  }
  existingUsernames.add(candidate)
  return candidate
}

/**
 * Generate a secure temporary password.
 * Format: 3 random words + 2 digits + special char (easy to type, meets complexity requirements).
 */
function generateTemporaryPassword(): string {
  const words = ['Sun', 'Moon', 'Star', 'Blue', 'Red', 'Oak', 'Bay', 'Fox', 'Elm', 'Sky',
    'Rain', 'Wind', 'Lake', 'Peak', 'Wave', 'Sage', 'Pine', 'Gold', 'Iron', 'Jade',
    'Lion', 'Bear', 'Hawk', 'Wolf', 'Rose', 'Fire', 'Mint', 'Ruby', 'Onyx', 'Teal']
  const specials = ['!', '@', '#', '$', '%', '&']
  const w1 = words[Math.floor(Math.random() * words.length)]
  const w2 = words[Math.floor(Math.random() * words.length)]
  const digits = String(Math.floor(Math.random() * 90) + 10)
  const sp = specials[Math.floor(Math.random() * specials.length)]
  return `${w1}${w2}${digits}${sp}`
}

/**
 * Generate credentials for a batch of imported employees.
 * Returns an array of credentials with username and temporary password for each.
 * SSO employees can be flagged to skip credential generation.
 */
export function generateBulkCredentials(
  employees: EmployeeImportRow[],
  existingEmails: string[] = []
): { credentials: EmployeeCredential[]; skipped: { email: string; reason: string }[] } {
  const credentials: EmployeeCredential[] = []
  const skipped: { email: string; reason: string }[] = []
  const usedUsernames = new Set<string>()
  const existingEmailSet = new Set(existingEmails.map(e => e.toLowerCase()))

  for (const emp of employees) {
    if (existingEmailSet.has(emp.email.toLowerCase())) {
      skipped.push({ email: emp.email, reason: 'Employee already exists' })
      continue
    }

    credentials.push({
      full_name: emp.full_name,
      email: emp.email,
      username: generateUsername(emp.full_name, emp.email, usedUsernames),
      temporary_password: generateTemporaryPassword(),
      must_change_password: true,
    })
  }

  return { credentials, skipped }
}

/**
 * Export credentials to CSV for admin download (secure distribution).
 */
export function exportCredentialsToCSV(credentials: EmployeeCredential[], filename: string = 'employee-credentials'): void {
  exportToCSV(
    credentials,
    [
      { header: 'Full Name', accessor: (c) => c.full_name },
      { header: 'Email', accessor: (c) => c.email },
      { header: 'Username', accessor: (c) => c.username },
      { header: 'Temporary Password', accessor: (c) => c.temporary_password },
      { header: 'Must Change Password', accessor: (c) => 'Yes' },
    ],
    filename
  )
}

// ============================================================
// MODULE-SPECIFIC EXPORT COLUMNS
// ============================================================

export const EMPLOYEE_EXPORT_COLUMNS = [
  { header: 'Name', accessor: (e: any) => e.profile?.full_name || '' },
  { header: 'Email', accessor: (e: any) => e.profile?.email || '' },
  { header: 'Job Title', accessor: (e: any) => e.job_title || '' },
  { header: 'Department', accessor: (e: any) => e.department_id || '' },
  { header: 'Country', accessor: (e: any) => e.country || '' },
  { header: 'Level', accessor: (e: any) => e.level || '' },
  { header: 'Hire Date', accessor: (e: any) => e.hire_date || '' },
  { header: 'Status', accessor: (e: any) => e.status || 'active' },
]

export const PAYROLL_EXPORT_COLUMNS = [
  { header: 'Period', accessor: (r: any) => r.period || '' },
  { header: 'Run Date', accessor: (r: any) => r.run_date || '' },
  { header: 'Gross Total', accessor: (r: any) => r.total_gross || 0 },
  { header: 'Net Total', accessor: (r: any) => r.total_net || 0 },
  { header: 'Total Deductions', accessor: (r: any) => r.total_deductions || 0 },
  { header: 'Employee Count', accessor: (r: any) => r.employee_count || 0 },
  { header: 'Currency', accessor: (r: any) => r.currency || 'USD' },
  { header: 'Status', accessor: (r: any) => r.status || '' },
]

export const EXPENSE_EXPORT_COLUMNS = [
  { header: 'Employee', accessor: (e: any) => e.employee_name || '' },
  { header: 'Title', accessor: (e: any) => e.title || '' },
  { header: 'Amount', accessor: (e: any) => e.total_amount || 0 },
  { header: 'Currency', accessor: (e: any) => e.currency || 'USD' },
  { header: 'Category', accessor: (e: any) => e.category || '' },
  { header: 'Status', accessor: (e: any) => e.status || '' },
  { header: 'Submitted', accessor: (e: any) => e.submitted_date || '' },
]

export const GOAL_EXPORT_COLUMNS = [
  { header: 'Title', accessor: (g: any) => g.title || '' },
  { header: 'Employee', accessor: (g: any) => g.employee_id || '' },
  { header: 'Category', accessor: (g: any) => g.category || '' },
  { header: 'Status', accessor: (g: any) => g.status || '' },
  { header: 'Progress', accessor: (g: any) => `${g.progress || 0}%` },
  { header: 'Due Date', accessor: (g: any) => g.due_date || '' },
]

export const LEAVE_EXPORT_COLUMNS = [
  { header: 'Employee', accessor: (l: any) => l.employee_id || '' },
  { header: 'Type', accessor: (l: any) => l.type || '' },
  { header: 'Start Date', accessor: (l: any) => l.start_date || '' },
  { header: 'End Date', accessor: (l: any) => l.end_date || '' },
  { header: 'Days', accessor: (l: any) => l.days || 0 },
  { header: 'Status', accessor: (l: any) => l.status || '' },
]

export const APPLICATION_EXPORT_COLUMNS = [
  { header: 'Candidate', accessor: (a: any) => a.candidate_name || '' },
  { header: 'Email', accessor: (a: any) => a.email || '' },
  { header: 'Position', accessor: (a: any) => a.job_posting_id || '' },
  { header: 'Status', accessor: (a: any) => a.status || '' },
  { header: 'Applied Date', accessor: (a: any) => a.applied_date || '' },
  { header: 'Source', accessor: (a: any) => a.source || '' },
]

// ============================================================
// EXCEL EXPORT
// ============================================================

/**
 * Export data as a formatted .xlsx file with auto-width columns.
 * Accepts the same ExportColumn format used by exportToCSV for consistency.
 */
export function exportToExcel<T>(
  data: T[],
  columns: { key: string; label: string }[],
  filename: string,
  exportColumns?: ExportColumn<T>[]
): void {
  if (data.length === 0) return

  const headers = columns.map(c => c.label)

  // Build rows using exportColumns accessors if provided, otherwise use key-based access
  const rows = data.map(row => {
    return columns.map((col, idx) => {
      if (exportColumns && exportColumns[idx]) {
        const val = exportColumns[idx].accessor(row)
        return val == null ? '' : String(val)
      }
      const val = (row as Record<string, unknown>)[col.key]
      return val == null ? '' : String(val)
    })
  })

  const sheetData = [headers, ...rows]
  const ws = XLSX.utils.aoa_to_sheet(sheetData)

  // Auto-width columns
  const colWidths = headers.map((header, colIdx) => {
    let maxLen = header.length
    for (const row of rows) {
      const cellLen = (row[colIdx] || '').length
      if (cellLen > maxLen) maxLen = cellLen
    }
    return { wch: Math.min(maxLen + 4, 50) }
  })
  ws['!cols'] = colWidths

  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, ws, 'Export')
  XLSX.writeFile(wb, `${filename}.xlsx`)
}

// ============================================================
// HELPERS
// ============================================================

function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  link.style.display = 'none'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
