/**
 * Export / Import Utilities
 *
 * Client-safe functions for exporting data to CSV/JSON/Excel and parsing CSV imports.
 * No database imports -- safe for 'use client' pages.
 */

import * as XLSX from 'xlsx'

// ============================================================
// CSV EXPORT
// ============================================================

interface ExportColumn<T> {
  header: string
  accessor: (row: T) => string | number | boolean | null | undefined
}

/**
 * Export an array of objects to CSV and trigger a browser download.
 */
export function exportToCSV<T>(
  data: T[],
  columns: ExportColumn<T>[],
  filename: string
): void {
  if (data.length === 0) return

  const headers = columns.map(c => escapeCSVField(c.header))
  const rows = data.map(row =>
    columns.map(col => {
      const val = col.accessor(row)
      return escapeCSVField(val == null ? '' : String(val))
    })
  )

  const csvContent = [headers.join(','), ...rows.map(r => r.join(','))].join('\n')
  downloadFile(csvContent, `${filename}.csv`, 'text/csv;charset=utf-8;')
}

function escapeCSVField(value: string): string {
  if (value.includes(',') || value.includes('"') || value.includes('\n')) {
    return `"${value.replace(/"/g, '""')}"`
  }
  return value
}

// ============================================================
// JSON EXPORT
// ============================================================

/**
 * Export data to JSON and trigger a browser download.
 */
export function exportToJSON<T>(data: T[], filename: string): void {
  const jsonContent = JSON.stringify(data, null, 2)
  downloadFile(jsonContent, `${filename}.json`, 'application/json')
}

// ============================================================
// PDF EXPORT (Basic)
// ============================================================

/**
 * Export a simple table to a printable HTML page (opens print dialog).
 */
export function exportToPrint<T>(
  data: T[],
  columns: ExportColumn<T>[],
  title: string
): void {
  const headerRow = columns.map(c => `<th style="padding:8px 12px;text-align:left;border-bottom:2px solid #333;font-size:12px;font-weight:600;color:#333">${c.header}</th>`).join('')
  const bodyRows = data.map(row => {
    const cells = columns.map(col => {
      const val = col.accessor(row)
      return `<td style="padding:6px 12px;border-bottom:1px solid #eee;font-size:11px;color:#555">${val == null ? '' : String(val)}</td>`
    }).join('')
    return `<tr>${cells}</tr>`
  }).join('')

  const html = `<!DOCTYPE html>
<html><head>
<title>${title} - Tempo Export</title>
<style>body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;padding:20px}table{border-collapse:collapse;width:100%}@media print{.no-print{display:none}}</style>
</head><body>
<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:20px">
  <div>
    <h1 style="margin:0;font-size:18px;color:#111">${title}</h1>
    <p style="margin:4px 0 0;font-size:12px;color:#999">Exported ${new Date().toLocaleDateString()} | ${data.length} records | Tempo Platform</p>
  </div>
  <button class="no-print" onclick="window.print()" style="padding:8px 16px;background:#004D40;color:#fff;border:none;border-radius:6px;cursor:pointer;font-size:12px">Print / Save as PDF</button>
</div>
<table>
  <thead><tr>${headerRow}</tr></thead>
  <tbody>${bodyRows}</tbody>
</table>
<div style="margin-top:20px;text-align:center">
  <p style="font-size:10px;color:#bbb">Generated by Tempo - Unified Workforce Platform</p>
</div>
</body></html>`

  const printWindow = window.open('', '_blank')
  if (printWindow) {
    printWindow.document.write(html)
    printWindow.document.close()
  }
}

// ============================================================
// CSV IMPORT / PARSING
// ============================================================

export interface ParsedCSV {
  headers: string[]
  rows: Record<string, string>[]
  errors: string[]
  totalRows: number
}

/**
 * Parse a CSV string into structured data.
 */
export function parseCSV(csvText: string): ParsedCSV {
  const errors: string[] = []
  const lines = csvText.split(/\r?\n/).filter(line => line.trim().length > 0)

  if (lines.length === 0) {
    return { headers: [], rows: [], errors: ['Empty CSV file'], totalRows: 0 }
  }

  const headers = parseCSVLine(lines[0]).map(h => h.trim())
  if (headers.length === 0) {
    return { headers: [], rows: [], errors: ['No headers found in CSV'], totalRows: 0 }
  }

  const rows: Record<string, string>[] = []
  for (let i = 1; i < lines.length; i++) {
    const values = parseCSVLine(lines[i])
    if (values.length !== headers.length) {
      errors.push(`Row ${i}: Expected ${headers.length} columns, got ${values.length}`)
      continue
    }
    const row: Record<string, string> = {}
    headers.forEach((header, idx) => {
      row[header] = values[idx]?.trim() || ''
    })
    rows.push(row)
  }

  return { headers, rows, errors, totalRows: lines.length - 1 }
}

function parseCSVLine(line: string): string[] {
  const result: string[] = []
  let current = ''
  let inQuotes = false

  for (let i = 0; i < line.length; i++) {
    const ch = line[i]
    if (inQuotes) {
      if (ch === '"') {
        if (i + 1 < line.length && line[i + 1] === '"') {
          current += '"'
          i++
        } else {
          inQuotes = false
        }
      } else {
        current += ch
      }
    } else {
      if (ch === '"') {
        inQuotes = true
      } else if (ch === ',') {
        result.push(current)
        current = ''
      } else {
        current += ch
      }
    }
  }
  result.push(current)
  return result
}

/**
 * Read a File object as CSV text.
 */
export function readFileAsCSV(file: File): Promise<ParsedCSV> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = (e) => {
      const text = e.target?.result as string
      resolve(parseCSV(text))
    }
    reader.onerror = () => reject(new Error('Failed to read file'))
    reader.readAsText(file)
  })
}

// ============================================================
// EMPLOYEE IMPORT MAPPING
// ============================================================

export interface EmployeeImportRow {
  // ── Core HR ──────────────────────────────────────────────
  full_name: string
  email: string
  personal_email?: string
  job_title: string
  department: string
  country: string
  level?: string
  hire_date: string
  phone?: string
  role?: string
  manager_email?: string
  location?: string
  employment_type?: string
  employee_id?: string
  date_of_birth?: string
  gender?: string
  marital_status?: string
  nationality?: string
  national_id?: string

  // ── Address ──────────────────────────────────────────────
  street_address?: string
  city?: string
  state_province?: string
  postal_code?: string
  address_country?: string

  // ── Payroll & Banking ────────────────────────────────────
  base_salary?: string
  pay_currency?: string
  pay_frequency?: string
  bank_name?: string
  bank_branch_code?: string
  bank_account_number?: string
  bank_account_name?: string
  mobile_money_provider?: string
  mobile_money_number?: string
  tax_id_number?: string
  social_security_number?: string
  pension_id?: string

  // ── Compensation ─────────────────────────────────────────
  bonus_target_percent?: string
  equity_stock_units?: string
  pay_band_grade?: string
  allowance_housing?: string
  allowance_transport?: string
  allowance_medical?: string

  // ── Benefits ─────────────────────────────────────────────
  medical_plan?: string
  dental_plan?: string
  life_insurance?: string
  number_of_dependents?: string

  // ── Time & Attendance ────────────────────────────────────
  work_schedule?: string
  weekly_hours?: string
  timezone?: string
  shift_type?: string

  // ── IT & Identity ────────────────────────────────────────
  ad_sso_username?: string
  corporate_email?: string
  device_preference?: string

  // ── Emergency Contact ────────────────────────────────────
  emergency_contact_name?: string
  emergency_contact_phone?: string
  emergency_contact_relationship?: string

  // ── Documents / Compliance ───────────────────────────────
  passport_number?: string
  work_permit_number?: string
  work_permit_expiry?: string
  highest_education?: string
  university_institution?: string
  previous_employer?: string

  // ── Notes ────────────────────────────────────────────────
  onboarding_notes?: string
}

const EMPLOYEE_FIELD_ALIASES: Record<string, string[]> = {
  // Core HR
  full_name: ['full_name', 'full name', 'name', 'employee_name', 'employee name', 'fullname'],
  email: ['email', 'email_address', 'email address', 'work_email', 'work email', 'employee_email', 'employee email'],
  personal_email: ['personal_email', 'personal email', 'private_email', 'private email', 'home_email', 'home email'],
  job_title: ['job_title', 'job title', 'title', 'position', 'role_title', 'role title'],
  department: ['department', 'dept', 'team', 'division'],
  country: ['country', 'country_code', 'country code'],
  level: ['level', 'job_level', 'job level', 'grade', 'band', 'seniority'],
  hire_date: ['hire_date', 'hire date', 'start_date', 'start date', 'join_date', 'join date', 'joining_date', 'joining date'],
  phone: ['phone', 'phone_number', 'phone number', 'mobile', 'telephone', 'tel'],
  role: ['role', 'access_role', 'access role', 'system_role', 'system role', 'permission'],
  manager_email: ['manager_email', 'manager email', 'manager', 'reports_to', 'reports to'],
  location: ['location', 'office', 'work_location', 'work location', 'office_location', 'office location'],
  employment_type: ['employment_type', 'employment type', 'emp_type', 'emp type', 'contract_type', 'contract type'],
  employee_id: ['employee_id', 'employee id', 'badge_number', 'badge number', 'emp_id', 'emp id', 'staff_id', 'staff id'],
  date_of_birth: ['date_of_birth', 'date of birth', 'dob', 'birthdate', 'birth_date', 'birth date', 'birthday'],
  gender: ['gender', 'sex'],
  marital_status: ['marital_status', 'marital status', 'civil_status', 'civil status'],
  nationality: ['nationality', 'citizenship'],
  national_id: ['national_id', 'national id', 'nin', 'id_number', 'id number'],

  // Address
  street_address: ['street_address', 'street address', 'address', 'street', 'address_line_1', 'address line 1'],
  city: ['city', 'town'],
  state_province: ['state_province', 'state/province', 'state', 'province', 'region'],
  postal_code: ['postal_code', 'postal code', 'zip_code', 'zip code', 'zip', 'postcode'],
  address_country: ['address_country', 'address country', 'residence_country', 'residence country'],

  // Payroll & Banking
  base_salary: ['base_salary', 'base salary', 'salary', 'annual_salary', 'annual salary', 'compensation'],
  pay_currency: ['pay_currency', 'pay currency', 'currency', 'salary_currency', 'salary currency'],
  pay_frequency: ['pay_frequency', 'pay frequency', 'payment_frequency', 'payment frequency'],
  bank_name: ['bank_name', 'bank name', 'bank'],
  bank_branch_code: ['bank_branch_code', 'bank branch code', 'swift', 'sort_code', 'sort code', 'routing_number', 'routing number', 'branch_code', 'branch code'],
  bank_account_number: ['bank_account_number', 'bank account number', 'account_number', 'account number', 'acct_number', 'acct number'],
  bank_account_name: ['bank_account_name', 'bank account name', 'account_name', 'account name', 'acct_name', 'acct name'],
  mobile_money_provider: ['mobile_money_provider', 'mobile money provider', 'momo_provider', 'momo provider', 'mobile_money', 'mobile money'],
  mobile_money_number: ['mobile_money_number', 'mobile money number', 'momo_number', 'momo number'],
  tax_id_number: ['tax_id_number', 'tax id number', 'tax_id', 'tax id', 'tin', 'kra_pin', 'kra pin'],
  social_security_number: ['social_security_number', 'social security number', 'ssn', 'nssf', 'nssf_number', 'nssf number'],
  pension_id: ['pension_id', 'pension id', 'pension_number', 'pension number', 'pencom', 'pencom_id', 'pencom id'],

  // Compensation
  bonus_target_percent: ['bonus_target_percent', 'bonus target %', 'bonus_target', 'bonus target', 'bonus_%', 'bonus %', 'bonus target percent'],
  equity_stock_units: ['equity_stock_units', 'equity/stock units', 'equity', 'stock_units', 'stock units', 'rsu', 'rsus'],
  pay_band_grade: ['pay_band_grade', 'pay band/grade', 'pay_band', 'pay band', 'pay_grade', 'pay grade', 'grade_code', 'grade code'],
  allowance_housing: ['allowance_housing', 'allowance - housing', 'housing_allowance', 'housing allowance'],
  allowance_transport: ['allowance_transport', 'allowance - transport', 'transport_allowance', 'transport allowance', 'travel_allowance', 'travel allowance'],
  allowance_medical: ['allowance_medical', 'allowance - medical', 'medical_allowance', 'medical allowance', 'health_allowance', 'health allowance'],

  // Benefits
  medical_plan: ['medical_plan', 'medical plan', 'health_plan', 'health plan', 'medical_insurance', 'medical insurance'],
  dental_plan: ['dental_plan', 'dental plan', 'dental_insurance', 'dental insurance'],
  life_insurance: ['life_insurance', 'life insurance'],
  number_of_dependents: ['number_of_dependents', 'number of dependents', 'dependents', 'num_dependents', 'num dependents'],

  // Time & Attendance
  work_schedule: ['work_schedule', 'work schedule', 'schedule', 'working_hours', 'working hours'],
  weekly_hours: ['weekly_hours', 'weekly hours', 'hours_per_week', 'hours per week'],
  timezone: ['timezone', 'time_zone', 'time zone', 'tz'],
  shift_type: ['shift_type', 'shift type', 'shift'],

  // IT & Identity
  ad_sso_username: ['ad_sso_username', 'ad/sso username', 'ad_username', 'ad username', 'sso_username', 'sso username', 'username', 'login'],
  corporate_email: ['corporate_email', 'corporate email', 'corp_email', 'corp email'],
  device_preference: ['device_preference', 'device preference', 'device', 'preferred_device', 'preferred device', 'laptop_preference', 'laptop preference'],

  // Emergency Contact
  emergency_contact_name: ['emergency_contact_name', 'emergency contact name', 'emergency_contact', 'emergency contact', 'emergency_name', 'emergency name', 'ice_name', 'ice name'],
  emergency_contact_phone: ['emergency_contact_phone', 'emergency contact phone', 'emergency_phone', 'emergency phone', 'ice_phone', 'ice phone'],
  emergency_contact_relationship: ['emergency_contact_relationship', 'emergency contact relationship', 'emergency_relationship', 'emergency relationship', 'ice_relationship', 'ice relationship'],

  // Documents / Compliance
  passport_number: ['passport_number', 'passport number', 'passport', 'passport_no', 'passport no'],
  work_permit_number: ['work_permit_number', 'work permit number', 'work_permit', 'work permit', 'visa_number', 'visa number'],
  work_permit_expiry: ['work_permit_expiry', 'work permit expiry', 'permit_expiry', 'permit expiry', 'visa_expiry', 'visa expiry'],
  highest_education: ['highest_education', 'highest education', 'education', 'education_level', 'education level', 'qualification'],
  university_institution: ['university_institution', 'university/institution', 'university', 'institution', 'school', 'alma_mater', 'alma mater'],
  previous_employer: ['previous_employer', 'previous employer', 'last_employer', 'last employer', 'prior_employer', 'prior employer'],

  // Notes
  onboarding_notes: ['onboarding_notes', 'onboarding notes', 'notes', 'comments', 'remarks'],
}

/**
 * Map CSV headers to employee fields using fuzzy matching.
 */
export function mapCSVToEmployeeFields(headers: string[]): Record<string, string> {
  const mapping: Record<string, string> = {}
  const lowerHeaders = headers.map(h => h.toLowerCase().trim())

  for (const [field, aliases] of Object.entries(EMPLOYEE_FIELD_ALIASES)) {
    for (const alias of aliases) {
      const idx = lowerHeaders.indexOf(alias.toLowerCase())
      if (idx !== -1) {
        mapping[field] = headers[idx]
        break
      }
    }
  }

  return mapping
}

/**
 * Validate imported employee rows.
 */
export function validateEmployeeImport(
  rows: Record<string, string>[],
  mapping: Record<string, string>
): { valid: EmployeeImportRow[]; errors: { row: number; message: string }[] } {
  const valid: EmployeeImportRow[] = []
  const errors: { row: number; message: string }[] = []

  rows.forEach((row, idx) => {
    const name = row[mapping.full_name]
    const email = row[mapping.email]

    if (!name || name.trim().length === 0) {
      errors.push({ row: idx + 2, message: 'Missing employee name' })
      return
    }
    if (!email || !email.includes('@')) {
      errors.push({ row: idx + 2, message: `Invalid email for ${name}` })
      return
    }

    // Helper to read an optional trimmed field
    const opt = (field: string) => {
      const header = mapping[field]
      if (!header) return undefined
      const val = row[header]?.trim()
      return val || undefined
    }

    valid.push({
      // Core HR
      full_name: name.trim(),
      email: email.trim().toLowerCase(),
      personal_email: opt('personal_email'),
      job_title: row[mapping.job_title]?.trim() || 'Team Member',
      department: row[mapping.department]?.trim() || 'General',
      country: row[mapping.country]?.trim() || 'US',
      level: opt('level'),
      hire_date: row[mapping.hire_date]?.trim() || new Date().toISOString().split('T')[0],
      phone: opt('phone'),
      role: opt('role'),
      manager_email: opt('manager_email'),
      location: opt('location'),
      employment_type: opt('employment_type'),
      employee_id: opt('employee_id'),
      date_of_birth: opt('date_of_birth'),
      gender: opt('gender'),
      marital_status: opt('marital_status'),
      nationality: opt('nationality'),
      national_id: opt('national_id'),

      // Address
      street_address: opt('street_address'),
      city: opt('city'),
      state_province: opt('state_province'),
      postal_code: opt('postal_code'),
      address_country: opt('address_country'),

      // Payroll & Banking
      base_salary: opt('base_salary'),
      pay_currency: opt('pay_currency'),
      pay_frequency: opt('pay_frequency'),
      bank_name: opt('bank_name'),
      bank_branch_code: opt('bank_branch_code'),
      bank_account_number: opt('bank_account_number'),
      bank_account_name: opt('bank_account_name'),
      mobile_money_provider: opt('mobile_money_provider'),
      mobile_money_number: opt('mobile_money_number'),
      tax_id_number: opt('tax_id_number'),
      social_security_number: opt('social_security_number'),
      pension_id: opt('pension_id'),

      // Compensation
      bonus_target_percent: opt('bonus_target_percent'),
      equity_stock_units: opt('equity_stock_units'),
      pay_band_grade: opt('pay_band_grade'),
      allowance_housing: opt('allowance_housing'),
      allowance_transport: opt('allowance_transport'),
      allowance_medical: opt('allowance_medical'),

      // Benefits
      medical_plan: opt('medical_plan'),
      dental_plan: opt('dental_plan'),
      life_insurance: opt('life_insurance'),
      number_of_dependents: opt('number_of_dependents'),

      // Time & Attendance
      work_schedule: opt('work_schedule'),
      weekly_hours: opt('weekly_hours'),
      timezone: opt('timezone'),
      shift_type: opt('shift_type'),

      // IT & Identity
      ad_sso_username: opt('ad_sso_username'),
      corporate_email: opt('corporate_email'),
      device_preference: opt('device_preference'),

      // Emergency Contact
      emergency_contact_name: opt('emergency_contact_name'),
      emergency_contact_phone: opt('emergency_contact_phone'),
      emergency_contact_relationship: opt('emergency_contact_relationship'),

      // Documents / Compliance
      passport_number: opt('passport_number'),
      work_permit_number: opt('work_permit_number'),
      work_permit_expiry: opt('work_permit_expiry'),
      highest_education: opt('highest_education'),
      university_institution: opt('university_institution'),
      previous_employer: opt('previous_employer'),

      // Notes
      onboarding_notes: opt('onboarding_notes'),
    })
  })

  return { valid, errors }
}

// ============================================================
// TEMPLATE DOWNLOAD
// ============================================================

/**
 * Triggers download of the CSV template from /templates/employee-import-template.csv
 */
export function downloadImportTemplate(): void {
  const link = document.createElement('a')
  link.href = '/templates/employee-import-template.csv'
  link.download = 'employee-import-template.csv'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}

// ============================================================
// CREDENTIAL GENERATION FOR BULK IMPORT
// ============================================================

export interface EmployeeCredential {
  full_name: string
  email: string
  username: string
  temporary_password: string
  must_change_password: boolean
}

/**
 * Generate a unique username from employee name and email.
 * Format: firstname.lastname (from email or name), with numeric suffix if duplicates exist.
 */
function generateUsername(fullName: string, email: string, existingUsernames: Set<string>): string {
  // Try email prefix first (most common format)
  const emailPrefix = email.split('@')[0].toLowerCase().replace(/[^a-z0-9._-]/g, '')
  if (emailPrefix && !existingUsernames.has(emailPrefix)) {
    existingUsernames.add(emailPrefix)
    return emailPrefix
  }

  // Fall back to name-based
  const parts = fullName.toLowerCase().trim().split(/\s+/)
  const base = parts.length >= 2
    ? `${parts[0]}.${parts[parts.length - 1]}`.replace(/[^a-z0-9._-]/g, '')
    : parts[0].replace(/[^a-z0-9._-]/g, '')

  let candidate = base
  let counter = 1
  while (existingUsernames.has(candidate)) {
    candidate = `${base}${counter}`
    counter++
  }
  existingUsernames.add(candidate)
  return candidate
}

/**
 * Generate a secure temporary password.
 * Format: 3 random words + 2 digits + special char (easy to type, meets complexity requirements).
 */
function generateTemporaryPassword(): string {
  const words = ['Sun', 'Moon', 'Star', 'Blue', 'Red', 'Oak', 'Bay', 'Fox', 'Elm', 'Sky',
    'Rain', 'Wind', 'Lake', 'Peak', 'Wave', 'Sage', 'Pine', 'Gold', 'Iron', 'Jade',
    'Lion', 'Bear', 'Hawk', 'Wolf', 'Rose', 'Fire', 'Mint', 'Ruby', 'Onyx', 'Teal']
  const specials = ['!', '@', '#', '$', '%', '&']
  const w1 = words[Math.floor(Math.random() * words.length)]
  const w2 = words[Math.floor(Math.random() * words.length)]
  const digits = String(Math.floor(Math.random() * 90) + 10)
  const sp = specials[Math.floor(Math.random() * specials.length)]
  return `${w1}${w2}${digits}${sp}`
}

/**
 * Generate credentials for a batch of imported employees.
 * Returns an array of credentials with username and temporary password for each.
 * SSO employees can be flagged to skip credential generation.
 */
export function generateBulkCredentials(
  employees: EmployeeImportRow[],
  existingEmails: string[] = []
): { credentials: EmployeeCredential[]; skipped: { email: string; reason: string }[] } {
  const credentials: EmployeeCredential[] = []
  const skipped: { email: string; reason: string }[] = []
  const usedUsernames = new Set<string>()
  const existingEmailSet = new Set(existingEmails.map(e => e.toLowerCase()))

  for (const emp of employees) {
    if (existingEmailSet.has(emp.email.toLowerCase())) {
      skipped.push({ email: emp.email, reason: 'Employee already exists' })
      continue
    }

    credentials.push({
      full_name: emp.full_name,
      email: emp.email,
      username: generateUsername(emp.full_name, emp.email, usedUsernames),
      temporary_password: generateTemporaryPassword(),
      must_change_password: true,
    })
  }

  return { credentials, skipped }
}

/**
 * Export credentials to CSV for admin download (secure distribution).
 */
export function exportCredentialsToCSV(credentials: EmployeeCredential[], filename: string = 'employee-credentials'): void {
  exportToCSV(
    credentials,
    [
      { header: 'Full Name', accessor: (c) => c.full_name },
      { header: 'Email', accessor: (c) => c.email },
      { header: 'Username', accessor: (c) => c.username },
      { header: 'Temporary Password', accessor: (c) => c.temporary_password },
      { header: 'Must Change Password', accessor: (c) => 'Yes' },
    ],
    filename
  )
}

// ============================================================
// MODULE-SPECIFIC EXPORT COLUMNS
// ============================================================

export const EMPLOYEE_EXPORT_COLUMNS = [
  { header: 'Name', accessor: (e: any) => e.profile?.full_name || '' },
  { header: 'Email', accessor: (e: any) => e.profile?.email || '' },
  { header: 'Job Title', accessor: (e: any) => e.job_title || '' },
  { header: 'Department', accessor: (e: any) => e.department_id || '' },
  { header: 'Country', accessor: (e: any) => e.country || '' },
  { header: 'Level', accessor: (e: any) => e.level || '' },
  { header: 'Hire Date', accessor: (e: any) => e.hire_date || '' },
  { header: 'Status', accessor: (e: any) => e.status || 'active' },
]

export const PAYROLL_EXPORT_COLUMNS = [
  { header: 'Period', accessor: (r: any) => r.period || '' },
  { header: 'Run Date', accessor: (r: any) => r.run_date || '' },
  { header: 'Gross Total', accessor: (r: any) => r.total_gross || 0 },
  { header: 'Net Total', accessor: (r: any) => r.total_net || 0 },
  { header: 'Total Deductions', accessor: (r: any) => r.total_deductions || 0 },
  { header: 'Employee Count', accessor: (r: any) => r.employee_count || 0 },
  { header: 'Currency', accessor: (r: any) => r.currency || 'USD' },
  { header: 'Status', accessor: (r: any) => r.status || '' },
]

export const EXPENSE_EXPORT_COLUMNS = [
  { header: 'Employee', accessor: (e: any) => e.employee_name || '' },
  { header: 'Title', accessor: (e: any) => e.title || '' },
  { header: 'Amount', accessor: (e: any) => e.total_amount || 0 },
  { header: 'Currency', accessor: (e: any) => e.currency || 'USD' },
  { header: 'Category', accessor: (e: any) => e.category || '' },
  { header: 'Status', accessor: (e: any) => e.status || '' },
  { header: 'Submitted', accessor: (e: any) => e.submitted_date || '' },
]

export const GOAL_EXPORT_COLUMNS = [
  { header: 'Title', accessor: (g: any) => g.title || '' },
  { header: 'Employee', accessor: (g: any) => g.employee_id || '' },
  { header: 'Category', accessor: (g: any) => g.category || '' },
  { header: 'Status', accessor: (g: any) => g.status || '' },
  { header: 'Progress', accessor: (g: any) => `${g.progress || 0}%` },
  { header: 'Due Date', accessor: (g: any) => g.due_date || '' },
]

export const LEAVE_EXPORT_COLUMNS = [
  { header: 'Employee', accessor: (l: any) => l.employee_id || '' },
  { header: 'Type', accessor: (l: any) => l.type || '' },
  { header: 'Start Date', accessor: (l: any) => l.start_date || '' },
  { header: 'End Date', accessor: (l: any) => l.end_date || '' },
  { header: 'Days', accessor: (l: any) => l.days || 0 },
  { header: 'Status', accessor: (l: any) => l.status || '' },
]

export const APPLICATION_EXPORT_COLUMNS = [
  { header: 'Candidate', accessor: (a: any) => a.candidate_name || '' },
  { header: 'Email', accessor: (a: any) => a.email || '' },
  { header: 'Position', accessor: (a: any) => a.job_posting_id || '' },
  { header: 'Status', accessor: (a: any) => a.status || '' },
  { header: 'Applied Date', accessor: (a: any) => a.applied_date || '' },
  { header: 'Source', accessor: (a: any) => a.source || '' },
]

// ============================================================
// EXCEL EXPORT
// ============================================================

/**
 * Export data as a formatted .xlsx file with auto-width columns.
 * Accepts the same ExportColumn format used by exportToCSV for consistency.
 */
export function exportToExcel<T>(
  data: T[],
  columns: { key: string; label: string }[],
  filename: string,
  exportColumns?: ExportColumn<T>[]
): void {
  if (data.length === 0) return

  const headers = columns.map(c => c.label)

  // Build rows using exportColumns accessors if provided, otherwise use key-based access
  const rows = data.map(row => {
    return columns.map((col, idx) => {
      if (exportColumns && exportColumns[idx]) {
        const val = exportColumns[idx].accessor(row)
        return val == null ? '' : String(val)
      }
      const val = (row as Record<string, unknown>)[col.key]
      return val == null ? '' : String(val)
    })
  })

  const sheetData = [headers, ...rows]
  const ws = XLSX.utils.aoa_to_sheet(sheetData)

  // Auto-width columns
  const colWidths = headers.map((header, colIdx) => {
    let maxLen = header.length
    for (const row of rows) {
      const cellLen = (row[colIdx] || '').length
      if (cellLen > maxLen) maxLen = cellLen
    }
    return { wch: Math.min(maxLen + 4, 50) }
  })
  ws['!cols'] = colWidths

  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, ws, 'Export')
  XLSX.writeFile(wb, `${filename}.xlsx`)
}

// ============================================================
// HELPERS
// ============================================================

function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  link.style.display = 'none'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
