/**
 * Export / Import Utilities
 *
 * Client-safe functions for exporting data to CSV/JSON and parsing CSV imports.
 * No database imports -- safe for 'use client' pages.
 */

// ============================================================
// CSV EXPORT
// ============================================================

interface ExportColumn<T> {
  header: string
  accessor: (row: T) => string | number | boolean | null | undefined
}

/**
 * Export an array of objects to CSV and trigger a browser download.
 */
export function exportToCSV<T>(
  data: T[],
  columns: ExportColumn<T>[],
  filename: string
): void {
  if (data.length === 0) return

  const headers = columns.map(c => escapeCSVField(c.header))
  const rows = data.map(row =>
    columns.map(col => {
      const val = col.accessor(row)
      return escapeCSVField(val == null ? '' : String(val))
    })
  )

  const csvContent = [headers.join(','), ...rows.map(r => r.join(','))].join('\n')
  downloadFile(csvContent, `${filename}.csv`, 'text/csv;charset=utf-8;')
}

function escapeCSVField(value: string): string {
  if (value.includes(',') || value.includes('"') || value.includes('\n')) {
    return `"${value.replace(/"/g, '""')}"`
  }
  return value
}

// ============================================================
// JSON EXPORT
// ============================================================

/**
 * Export data to JSON and trigger a browser download.
 */
export function exportToJSON<T>(data: T[], filename: string): void {
  const jsonContent = JSON.stringify(data, null, 2)
  downloadFile(jsonContent, `${filename}.json`, 'application/json')
}

// ============================================================
// PDF EXPORT (Basic)
// ============================================================

/**
 * Export a simple table to a printable HTML page (opens print dialog).
 */
export function exportToPrint<T>(
  data: T[],
  columns: ExportColumn<T>[],
  title: string
): void {
  const headerRow = columns.map(c => `<th style="padding:8px 12px;text-align:left;border-bottom:2px solid #333;font-size:12px;font-weight:600;color:#333">${c.header}</th>`).join('')
  const bodyRows = data.map(row => {
    const cells = columns.map(col => {
      const val = col.accessor(row)
      return `<td style="padding:6px 12px;border-bottom:1px solid #eee;font-size:11px;color:#555">${val == null ? '' : String(val)}</td>`
    }).join('')
    return `<tr>${cells}</tr>`
  }).join('')

  const html = `<!DOCTYPE html>
<html><head>
<title>${title} - Tempo Export</title>
<style>body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;padding:20px}table{border-collapse:collapse;width:100%}@media print{.no-print{display:none}}</style>
</head><body>
<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:20px">
  <div>
    <h1 style="margin:0;font-size:18px;color:#111">${title}</h1>
    <p style="margin:4px 0 0;font-size:12px;color:#999">Exported ${new Date().toLocaleDateString()} | ${data.length} records | Tempo Platform</p>
  </div>
  <button class="no-print" onclick="window.print()" style="padding:8px 16px;background:#ea580c;color:#fff;border:none;border-radius:6px;cursor:pointer;font-size:12px">Print / Save as PDF</button>
</div>
<table>
  <thead><tr>${headerRow}</tr></thead>
  <tbody>${bodyRows}</tbody>
</table>
<div style="margin-top:20px;text-align:center">
  <p style="font-size:10px;color:#bbb">Generated by Tempo - Unified Workforce Platform</p>
</div>
</body></html>`

  const printWindow = window.open('', '_blank')
  if (printWindow) {
    printWindow.document.write(html)
    printWindow.document.close()
  }
}

// ============================================================
// CSV IMPORT / PARSING
// ============================================================

export interface ParsedCSV {
  headers: string[]
  rows: Record<string, string>[]
  errors: string[]
  totalRows: number
}

/**
 * Parse a CSV string into structured data.
 */
export function parseCSV(csvText: string): ParsedCSV {
  const errors: string[] = []
  const lines = csvText.split(/\r?\n/).filter(line => line.trim().length > 0)

  if (lines.length === 0) {
    return { headers: [], rows: [], errors: ['Empty CSV file'], totalRows: 0 }
  }

  const headers = parseCSVLine(lines[0]).map(h => h.trim())
  if (headers.length === 0) {
    return { headers: [], rows: [], errors: ['No headers found in CSV'], totalRows: 0 }
  }

  const rows: Record<string, string>[] = []
  for (let i = 1; i < lines.length; i++) {
    const values = parseCSVLine(lines[i])
    if (values.length !== headers.length) {
      errors.push(`Row ${i}: Expected ${headers.length} columns, got ${values.length}`)
      continue
    }
    const row: Record<string, string> = {}
    headers.forEach((header, idx) => {
      row[header] = values[idx]?.trim() || ''
    })
    rows.push(row)
  }

  return { headers, rows, errors, totalRows: lines.length - 1 }
}

function parseCSVLine(line: string): string[] {
  const result: string[] = []
  let current = ''
  let inQuotes = false

  for (let i = 0; i < line.length; i++) {
    const ch = line[i]
    if (inQuotes) {
      if (ch === '"') {
        if (i + 1 < line.length && line[i + 1] === '"') {
          current += '"'
          i++
        } else {
          inQuotes = false
        }
      } else {
        current += ch
      }
    } else {
      if (ch === '"') {
        inQuotes = true
      } else if (ch === ',') {
        result.push(current)
        current = ''
      } else {
        current += ch
      }
    }
  }
  result.push(current)
  return result
}

/**
 * Read a File object as CSV text.
 */
export function readFileAsCSV(file: File): Promise<ParsedCSV> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = (e) => {
      const text = e.target?.result as string
      resolve(parseCSV(text))
    }
    reader.onerror = () => reject(new Error('Failed to read file'))
    reader.readAsText(file)
  })
}

// ============================================================
// EMPLOYEE IMPORT MAPPING
// ============================================================

export interface EmployeeImportRow {
  full_name: string
  email: string
  job_title: string
  department: string
  country: string
  hire_date: string
  phone?: string
  location?: string
  level?: string
  manager_email?: string
}

const EMPLOYEE_FIELD_ALIASES: Record<string, string[]> = {
  full_name: ['full_name', 'name', 'employee_name', 'fullname', 'full name'],
  email: ['email', 'email_address', 'work_email', 'employee_email'],
  job_title: ['job_title', 'title', 'position', 'role', 'job title'],
  department: ['department', 'dept', 'team', 'division'],
  country: ['country', 'country_code', 'location_country'],
  hire_date: ['hire_date', 'start_date', 'join_date', 'hire date', 'start date'],
  phone: ['phone', 'phone_number', 'mobile', 'telephone'],
  location: ['location', 'office', 'city', 'work_location'],
  level: ['level', 'job_level', 'grade', 'band'],
  manager_email: ['manager_email', 'manager', 'reports_to', 'manager email'],
}

/**
 * Map CSV headers to employee fields using fuzzy matching.
 */
export function mapCSVToEmployeeFields(headers: string[]): Record<string, string> {
  const mapping: Record<string, string> = {}
  const lowerHeaders = headers.map(h => h.toLowerCase().trim())

  for (const [field, aliases] of Object.entries(EMPLOYEE_FIELD_ALIASES)) {
    for (const alias of aliases) {
      const idx = lowerHeaders.indexOf(alias.toLowerCase())
      if (idx !== -1) {
        mapping[field] = headers[idx]
        break
      }
    }
  }

  return mapping
}

/**
 * Validate imported employee rows.
 */
export function validateEmployeeImport(
  rows: Record<string, string>[],
  mapping: Record<string, string>
): { valid: EmployeeImportRow[]; errors: { row: number; message: string }[] } {
  const valid: EmployeeImportRow[] = []
  const errors: { row: number; message: string }[] = []

  rows.forEach((row, idx) => {
    const name = row[mapping.full_name]
    const email = row[mapping.email]

    if (!name || name.trim().length === 0) {
      errors.push({ row: idx + 2, message: 'Missing employee name' })
      return
    }
    if (!email || !email.includes('@')) {
      errors.push({ row: idx + 2, message: `Invalid email for ${name}` })
      return
    }

    valid.push({
      full_name: name.trim(),
      email: email.trim().toLowerCase(),
      job_title: row[mapping.job_title]?.trim() || 'Team Member',
      department: row[mapping.department]?.trim() || 'General',
      country: row[mapping.country]?.trim() || 'US',
      hire_date: row[mapping.hire_date]?.trim() || new Date().toISOString().split('T')[0],
      phone: row[mapping.phone]?.trim(),
      location: row[mapping.location]?.trim(),
      level: row[mapping.level]?.trim(),
      manager_email: row[mapping.manager_email]?.trim(),
    })
  })

  return { valid, errors }
}

// ============================================================
// MODULE-SPECIFIC EXPORT COLUMNS
// ============================================================

export const EMPLOYEE_EXPORT_COLUMNS = [
  { header: 'Name', accessor: (e: any) => e.profile?.full_name || '' },
  { header: 'Email', accessor: (e: any) => e.profile?.email || '' },
  { header: 'Job Title', accessor: (e: any) => e.job_title || '' },
  { header: 'Department', accessor: (e: any) => e.department_id || '' },
  { header: 'Country', accessor: (e: any) => e.country || '' },
  { header: 'Level', accessor: (e: any) => e.level || '' },
  { header: 'Hire Date', accessor: (e: any) => e.hire_date || '' },
  { header: 'Status', accessor: (e: any) => e.status || 'active' },
]

export const PAYROLL_EXPORT_COLUMNS = [
  { header: 'Period', accessor: (r: any) => r.period || '' },
  { header: 'Run Date', accessor: (r: any) => r.run_date || '' },
  { header: 'Gross Total', accessor: (r: any) => r.total_gross || 0 },
  { header: 'Net Total', accessor: (r: any) => r.total_net || 0 },
  { header: 'Total Deductions', accessor: (r: any) => r.total_deductions || 0 },
  { header: 'Employee Count', accessor: (r: any) => r.employee_count || 0 },
  { header: 'Currency', accessor: (r: any) => r.currency || 'USD' },
  { header: 'Status', accessor: (r: any) => r.status || '' },
]

export const EXPENSE_EXPORT_COLUMNS = [
  { header: 'Employee', accessor: (e: any) => e.employee_name || '' },
  { header: 'Title', accessor: (e: any) => e.title || '' },
  { header: 'Amount', accessor: (e: any) => e.total_amount || 0 },
  { header: 'Currency', accessor: (e: any) => e.currency || 'USD' },
  { header: 'Category', accessor: (e: any) => e.category || '' },
  { header: 'Status', accessor: (e: any) => e.status || '' },
  { header: 'Submitted', accessor: (e: any) => e.submitted_date || '' },
]

export const GOAL_EXPORT_COLUMNS = [
  { header: 'Title', accessor: (g: any) => g.title || '' },
  { header: 'Employee', accessor: (g: any) => g.employee_id || '' },
  { header: 'Category', accessor: (g: any) => g.category || '' },
  { header: 'Status', accessor: (g: any) => g.status || '' },
  { header: 'Progress', accessor: (g: any) => `${g.progress || 0}%` },
  { header: 'Due Date', accessor: (g: any) => g.due_date || '' },
]

export const LEAVE_EXPORT_COLUMNS = [
  { header: 'Employee', accessor: (l: any) => l.employee_id || '' },
  { header: 'Type', accessor: (l: any) => l.type || '' },
  { header: 'Start Date', accessor: (l: any) => l.start_date || '' },
  { header: 'End Date', accessor: (l: any) => l.end_date || '' },
  { header: 'Days', accessor: (l: any) => l.days || 0 },
  { header: 'Status', accessor: (l: any) => l.status || '' },
]

export const APPLICATION_EXPORT_COLUMNS = [
  { header: 'Candidate', accessor: (a: any) => a.candidate_name || '' },
  { header: 'Email', accessor: (a: any) => a.email || '' },
  { header: 'Position', accessor: (a: any) => a.job_posting_id || '' },
  { header: 'Status', accessor: (a: any) => a.status || '' },
  { header: 'Applied Date', accessor: (a: any) => a.applied_date || '' },
  { header: 'Source', accessor: (a: any) => a.source || '' },
]

// ============================================================
// HELPERS
// ============================================================

function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  link.style.display = 'none'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
