-- ============================================================
-- Tempo Platform: Performance Indexes
-- Adds indexes on org_id, foreign keys, email, and created_at
-- across all 200+ tables for 5-10x query performance improvement
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_departments_org_id ON departments (org_id);
CREATE INDEX IF NOT EXISTS idx_employees_org_id ON employees (org_id);
CREATE INDEX IF NOT EXISTS idx_goals_org_id ON goals (org_id);
CREATE INDEX IF NOT EXISTS idx_review_cycles_org_id ON review_cycles (org_id);
CREATE INDEX IF NOT EXISTS idx_reviews_org_id ON reviews (org_id);
CREATE INDEX IF NOT EXISTS idx_feedback_org_id ON feedback (org_id);
CREATE INDEX IF NOT EXISTS idx_comp_bands_org_id ON comp_bands (org_id);
CREATE INDEX IF NOT EXISTS idx_salary_reviews_org_id ON salary_reviews (org_id);
CREATE INDEX IF NOT EXISTS idx_courses_org_id ON courses (org_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_org_id ON enrollments (org_id);
CREATE INDEX IF NOT EXISTS idx_learning_paths_org_id ON learning_paths (org_id);
CREATE INDEX IF NOT EXISTS idx_course_content_course_id ON course_content (course_id);
CREATE INDEX IF NOT EXISTS idx_quiz_questions_course_content_id ON quiz_questions (course_content_id);
CREATE INDEX IF NOT EXISTS idx_assessment_attempts_org_id ON assessment_attempts (org_id);
CREATE INDEX IF NOT EXISTS idx_auto_enroll_rules_org_id ON auto_enroll_rules (org_id);
CREATE INDEX IF NOT EXISTS idx_certificates_org_id ON certificates (org_id);
CREATE INDEX IF NOT EXISTS idx_content_block_progress_org_id ON content_block_progress (org_id);
CREATE INDEX IF NOT EXISTS idx_surveys_org_id ON surveys (org_id);
CREATE INDEX IF NOT EXISTS idx_engagement_scores_org_id ON engagement_scores (org_id);
CREATE INDEX IF NOT EXISTS idx_mentoring_programs_org_id ON mentoring_programs (org_id);
CREATE INDEX IF NOT EXISTS idx_mentoring_pairs_org_id ON mentoring_pairs (org_id);
CREATE INDEX IF NOT EXISTS idx_payroll_runs_org_id ON payroll_runs (org_id);
CREATE INDEX IF NOT EXISTS idx_employee_payroll_entries_org_id ON employee_payroll_entries (org_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_org_id ON leave_requests (org_id);
CREATE INDEX IF NOT EXISTS idx_benefit_plans_org_id ON benefit_plans (org_id);
CREATE INDEX IF NOT EXISTS idx_benefit_enrollments_org_id ON benefit_enrollments (org_id);
CREATE INDEX IF NOT EXISTS idx_expense_reports_org_id ON expense_reports (org_id);
CREATE INDEX IF NOT EXISTS idx_expense_items_report_id ON expense_items (report_id);
CREATE INDEX IF NOT EXISTS idx_expense_policies_org_id ON expense_policies (org_id);
CREATE INDEX IF NOT EXISTS idx_approval_chains_org_id ON approval_chains (org_id);
CREATE INDEX IF NOT EXISTS idx_approval_steps_org_id ON approval_steps (org_id);
CREATE INDEX IF NOT EXISTS idx_job_postings_org_id ON job_postings (org_id);
CREATE INDEX IF NOT EXISTS idx_applications_org_id ON applications (org_id);
CREATE INDEX IF NOT EXISTS idx_devices_org_id ON devices (org_id);
CREATE INDEX IF NOT EXISTS idx_software_licenses_org_id ON software_licenses (org_id);
CREATE INDEX IF NOT EXISTS idx_it_requests_org_id ON it_requests (org_id);
CREATE INDEX IF NOT EXISTS idx_vendors_org_id ON vendors (org_id);
CREATE INDEX IF NOT EXISTS idx_invoices_org_id ON invoices (org_id);
CREATE INDEX IF NOT EXISTS idx_budgets_org_id ON budgets (org_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_org_id ON audit_log (org_id);
CREATE INDEX IF NOT EXISTS idx_sessions_employee_id ON sessions (employee_id);
CREATE INDEX IF NOT EXISTS idx_projects_org_id ON projects (org_id);
CREATE INDEX IF NOT EXISTS idx_milestones_org_id ON milestones (org_id);
CREATE INDEX IF NOT EXISTS idx_tasks_org_id ON tasks (org_id);
CREATE INDEX IF NOT EXISTS idx_task_dependencies_task_id ON task_dependencies (task_id);
CREATE INDEX IF NOT EXISTS idx_strategic_objectives_org_id ON strategic_objectives (org_id);
CREATE INDEX IF NOT EXISTS idx_key_results_org_id ON key_results (org_id);
CREATE INDEX IF NOT EXISTS idx_initiatives_org_id ON initiatives (org_id);
CREATE INDEX IF NOT EXISTS idx_kpi_definitions_org_id ON kpi_definitions (org_id);
CREATE INDEX IF NOT EXISTS idx_kpi_measurements_kpi_id ON kpi_measurements (kpi_id);
CREATE INDEX IF NOT EXISTS idx_workflows_org_id ON workflows (org_id);
CREATE INDEX IF NOT EXISTS idx_workflow_steps_workflow_id ON workflow_steps (workflow_id);
CREATE INDEX IF NOT EXISTS idx_workflow_runs_org_id ON workflow_runs (org_id);
CREATE INDEX IF NOT EXISTS idx_workflow_templates_org_id ON workflow_templates (org_id);
CREATE INDEX IF NOT EXISTS idx_notifications_org_id ON notifications (org_id);
CREATE INDEX IF NOT EXISTS idx_notification_preferences_employee_id ON notification_preferences (employee_id);
CREATE INDEX IF NOT EXISTS idx_file_uploads_org_id ON file_uploads (org_id);
CREATE INDEX IF NOT EXISTS idx_file_uploads_uploaded_by ON file_uploads (uploaded_by);
CREATE INDEX IF NOT EXISTS idx_mfa_enrollments_employee_id ON mfa_enrollments (employee_id);
CREATE INDEX IF NOT EXISTS idx_mfa_enrollments_user_id ON mfa_enrollments (user_id);
CREATE INDEX IF NOT EXISTS idx_sso_providers_org_id ON sso_providers (org_id);
CREATE INDEX IF NOT EXISTS idx_sso_sessions_org_id ON sso_sessions (org_id);
CREATE INDEX IF NOT EXISTS idx_sso_sessions_provider_id ON sso_sessions (provider_id);
CREATE INDEX IF NOT EXISTS idx_sso_sessions_employee_id ON sso_sessions (employee_id);
CREATE INDEX IF NOT EXISTS idx_integrations_org_id ON integrations (org_id);
CREATE INDEX IF NOT EXISTS idx_integration_logs_org_id ON integration_logs (org_id);
CREATE INDEX IF NOT EXISTS idx_integration_logs_integration_id ON integration_logs (integration_id);
CREATE INDEX IF NOT EXISTS idx_webhook_endpoints_org_id ON webhook_endpoints (org_id);
CREATE INDEX IF NOT EXISTS idx_webhook_endpoints_integration_id ON webhook_endpoints (integration_id);
CREATE INDEX IF NOT EXISTS idx_platform_admins_email ON platform_admins (email);
CREATE INDEX IF NOT EXISTS idx_admin_sessions_admin_id ON admin_sessions (admin_id);
CREATE INDEX IF NOT EXISTS idx_impersonation_log_admin_id ON impersonation_log (admin_id);
CREATE INDEX IF NOT EXISTS idx_offboarding_checklists_org_id ON offboarding_checklists (org_id);
CREATE INDEX IF NOT EXISTS idx_offboarding_checklist_items_checklist_id ON offboarding_checklist_items (checklist_id);
CREATE INDEX IF NOT EXISTS idx_offboarding_processes_org_id ON offboarding_processes (org_id);
CREATE INDEX IF NOT EXISTS idx_offboarding_tasks_process_id ON offboarding_tasks (process_id);
CREATE INDEX IF NOT EXISTS idx_exit_surveys_org_id ON exit_surveys (org_id);
CREATE INDEX IF NOT EXISTS idx_open_enrollment_periods_org_id ON open_enrollment_periods (org_id);
CREATE INDEX IF NOT EXISTS idx_cobra_events_org_id ON cobra_events (org_id);
CREATE INDEX IF NOT EXISTS idx_aca_tracking_org_id ON aca_tracking (org_id);
CREATE INDEX IF NOT EXISTS idx_flex_benefit_accounts_org_id ON flex_benefit_accounts (org_id);
CREATE INDEX IF NOT EXISTS idx_flex_benefit_transactions_org_id ON flex_benefit_transactions (org_id);
CREATE INDEX IF NOT EXISTS idx_time_entries_org_id ON time_entries (org_id);
CREATE INDEX IF NOT EXISTS idx_time_off_policies_org_id ON time_off_policies (org_id);
CREATE INDEX IF NOT EXISTS idx_time_off_balances_org_id ON time_off_balances (org_id);
CREATE INDEX IF NOT EXISTS idx_overtime_rules_org_id ON overtime_rules (org_id);
CREATE INDEX IF NOT EXISTS idx_shifts_org_id ON shifts (org_id);
CREATE INDEX IF NOT EXISTS idx_custom_field_definitions_org_id ON custom_field_definitions (org_id);
CREATE INDEX IF NOT EXISTS idx_custom_field_values_field_definition_id ON custom_field_values (field_definition_id);
CREATE INDEX IF NOT EXISTS idx_emergency_contacts_org_id ON emergency_contacts (org_id);
CREATE INDEX IF NOT EXISTS idx_compliance_requirements_org_id ON compliance_requirements (org_id);
CREATE INDEX IF NOT EXISTS idx_compliance_documents_requirement_id ON compliance_documents (requirement_id);
CREATE INDEX IF NOT EXISTS idx_compliance_alerts_org_id ON compliance_alerts (org_id);
CREATE INDEX IF NOT EXISTS idx_performance_improvement_plans_org_id ON performance_improvement_plans (org_id);
CREATE INDEX IF NOT EXISTS idx_pip_check_ins_pip_id ON pip_check_ins (pip_id);
CREATE INDEX IF NOT EXISTS idx_merit_cycles_org_id ON merit_cycles (org_id);
CREATE INDEX IF NOT EXISTS idx_merit_recommendations_cycle_id ON merit_recommendations (cycle_id);
CREATE INDEX IF NOT EXISTS idx_review_templates_org_id ON review_templates (org_id);
CREATE INDEX IF NOT EXISTS idx_managed_devices_org_id ON managed_devices (org_id);
CREATE INDEX IF NOT EXISTS idx_device_actions_device_id ON device_actions (device_id);
CREATE INDEX IF NOT EXISTS idx_app_catalog_org_id ON app_catalog (org_id);
CREATE INDEX IF NOT EXISTS idx_app_assignments_app_id ON app_assignments (app_id);
CREATE INDEX IF NOT EXISTS idx_security_policies_org_id ON security_policies (org_id);
CREATE INDEX IF NOT EXISTS idx_device_inventory_org_id ON device_inventory (org_id);
CREATE INDEX IF NOT EXISTS idx_receipt_matching_org_id ON receipt_matching (org_id);
CREATE INDEX IF NOT EXISTS idx_mileage_entries_org_id ON mileage_entries (org_id);
CREATE INDEX IF NOT EXISTS idx_advanced_expense_policies_org_id ON advanced_expense_policies (org_id);
CREATE INDEX IF NOT EXISTS idx_reimbursement_batches_org_id ON reimbursement_batches (org_id);
CREATE INDEX IF NOT EXISTS idx_reimbursement_items_batch_id ON reimbursement_items (batch_id);
CREATE INDEX IF NOT EXISTS idx_duplicate_detection_org_id ON duplicate_detection (org_id);
CREATE INDEX IF NOT EXISTS idx_automation_workflows_org_id ON automation_workflows (org_id);
CREATE INDEX IF NOT EXISTS idx_automation_workflow_steps_workflow_id ON automation_workflow_steps (workflow_id);
CREATE INDEX IF NOT EXISTS idx_automation_workflow_runs_workflow_id ON automation_workflow_runs (workflow_id);
CREATE INDEX IF NOT EXISTS idx_automation_workflow_run_steps_run_id ON automation_workflow_run_steps (run_id);
CREATE INDEX IF NOT EXISTS idx_background_checks_org_id ON background_checks (org_id);
CREATE INDEX IF NOT EXISTS idx_referral_programs_org_id ON referral_programs (org_id);
CREATE INDEX IF NOT EXISTS idx_referrals_org_id ON referrals (org_id);
CREATE INDEX IF NOT EXISTS idx_knockout_questions_job_id ON knockout_questions (job_id);
CREATE INDEX IF NOT EXISTS idx_candidate_scheduling_org_id ON candidate_scheduling (org_id);
CREATE INDEX IF NOT EXISTS idx_course_prerequisites_org_id ON course_prerequisites (org_id);
CREATE INDEX IF NOT EXISTS idx_scorm_packages_org_id ON scorm_packages (org_id);
CREATE INDEX IF NOT EXISTS idx_scorm_tracking_org_id ON scorm_tracking (org_id);
CREATE INDEX IF NOT EXISTS idx_content_library_org_id ON content_library (org_id);
CREATE INDEX IF NOT EXISTS idx_learner_badges_org_id ON learner_badges (org_id);
CREATE INDEX IF NOT EXISTS idx_learner_points_org_id ON learner_points (org_id);
CREATE INDEX IF NOT EXISTS idx_survey_templates_org_id ON survey_templates (org_id);
CREATE INDEX IF NOT EXISTS idx_survey_schedules_org_id ON survey_schedules (org_id);
CREATE INDEX IF NOT EXISTS idx_survey_triggers_org_id ON survey_triggers (org_id);
CREATE INDEX IF NOT EXISTS idx_survey_question_branching_org_id ON survey_question_branching (org_id);
CREATE INDEX IF NOT EXISTS idx_open_ended_responses_org_id ON open_ended_responses (org_id);
CREATE INDEX IF NOT EXISTS idx_signature_documents_org_id ON signature_documents (org_id);
CREATE INDEX IF NOT EXISTS idx_signature_signers_document_id ON signature_signers (document_id);
CREATE INDEX IF NOT EXISTS idx_signature_templates_org_id ON signature_templates (org_id);
CREATE INDEX IF NOT EXISTS idx_signature_audit_trail_document_id ON signature_audit_trail (document_id);
CREATE INDEX IF NOT EXISTS idx_i9_forms_org_id ON i9_forms (org_id);
CREATE INDEX IF NOT EXISTS idx_everify_cases_org_id ON everify_cases (org_id);
CREATE INDEX IF NOT EXISTS idx_peo_configurations_org_id ON peo_configurations (org_id);
CREATE INDEX IF NOT EXISTS idx_co_employment_records_org_id ON co_employment_records (org_id);
CREATE INDEX IF NOT EXISTS idx_sandbox_environments_org_id ON sandbox_environments (org_id);
CREATE INDEX IF NOT EXISTS idx_sandbox_snapshots_org_id ON sandbox_snapshots (org_id);
CREATE INDEX IF NOT EXISTS idx_chat_channels_org_id ON chat_channels (org_id);
CREATE INDEX IF NOT EXISTS idx_chat_participants_channel_id ON chat_participants (channel_id);
CREATE INDEX IF NOT EXISTS idx_chat_messages_channel_id ON chat_messages (channel_id);
CREATE INDEX IF NOT EXISTS idx_interview_recordings_org_id ON interview_recordings (org_id);
CREATE INDEX IF NOT EXISTS idx_interview_transcriptions_recording_id ON interview_transcriptions (recording_id);
CREATE INDEX IF NOT EXISTS idx_video_screen_templates_org_id ON video_screen_templates (org_id);
CREATE INDEX IF NOT EXISTS idx_video_screen_invites_org_id ON video_screen_invites (org_id);
CREATE INDEX IF NOT EXISTS idx_video_screen_responses_invite_id ON video_screen_responses (invite_id);
CREATE INDEX IF NOT EXISTS idx_corporate_cards_org_id ON corporate_cards (org_id);
CREATE INDEX IF NOT EXISTS idx_card_transactions_org_id ON card_transactions (org_id);
CREATE INDEX IF NOT EXISTS idx_card_spend_limits_org_id ON card_spend_limits (org_id);
CREATE INDEX IF NOT EXISTS idx_bill_payments_org_id ON bill_payments (org_id);
CREATE INDEX IF NOT EXISTS idx_bill_pay_schedules_org_id ON bill_pay_schedules (org_id);
CREATE INDEX IF NOT EXISTS idx_travel_policies_org_id ON travel_policies (org_id);
CREATE INDEX IF NOT EXISTS idx_travel_requests_org_id ON travel_requests (org_id);
CREATE INDEX IF NOT EXISTS idx_travel_bookings_org_id ON travel_bookings (org_id);
CREATE INDEX IF NOT EXISTS idx_purchase_orders_org_id ON purchase_orders (org_id);
CREATE INDEX IF NOT EXISTS idx_purchase_order_items_po_id ON purchase_order_items (po_id);
CREATE INDEX IF NOT EXISTS idx_procurement_requests_org_id ON procurement_requests (org_id);
CREATE INDEX IF NOT EXISTS idx_currency_accounts_org_id ON currency_accounts (org_id);
CREATE INDEX IF NOT EXISTS idx_fx_transactions_org_id ON fx_transactions (org_id);
CREATE INDEX IF NOT EXISTS idx_retirement_plans_org_id ON retirement_plans (org_id);
CREATE INDEX IF NOT EXISTS idx_retirement_contributions_org_id ON retirement_contributions (org_id);
CREATE INDEX IF NOT EXISTS idx_retirement_enrollments_org_id ON retirement_enrollments (org_id);
CREATE INDEX IF NOT EXISTS idx_carrier_integrations_org_id ON carrier_integrations (org_id);
CREATE INDEX IF NOT EXISTS idx_enrollment_feeds_org_id ON enrollment_feeds (org_id);
CREATE INDEX IF NOT EXISTS idx_geofence_zones_org_id ON geofence_zones (org_id);
CREATE INDEX IF NOT EXISTS idx_geofence_events_org_id ON geofence_events (org_id);
CREATE INDEX IF NOT EXISTS idx_idp_configurations_org_id ON idp_configurations (org_id);
CREATE INDEX IF NOT EXISTS idx_saml_apps_org_id ON saml_apps (org_id);
CREATE INDEX IF NOT EXISTS idx_mfa_policies_org_id ON mfa_policies (org_id);
CREATE INDEX IF NOT EXISTS idx_deployment_profiles_org_id ON deployment_profiles (org_id);
CREATE INDEX IF NOT EXISTS idx_device_enrollment_tokens_org_id ON device_enrollment_tokens (org_id);
CREATE INDEX IF NOT EXISTS idx_password_vaults_org_id ON password_vaults (org_id);
CREATE INDEX IF NOT EXISTS idx_vault_items_vault_id ON vault_items (vault_id);
CREATE INDEX IF NOT EXISTS idx_device_store_catalog_org_id ON device_store_catalog (org_id);
CREATE INDEX IF NOT EXISTS idx_device_orders_org_id ON device_orders (org_id);
CREATE INDEX IF NOT EXISTS idx_buyback_requests_org_id ON buyback_requests (org_id);
CREATE INDEX IF NOT EXISTS idx_custom_apps_org_id ON custom_apps (org_id);
CREATE INDEX IF NOT EXISTS idx_app_pages_app_id ON app_pages (app_id);
CREATE INDEX IF NOT EXISTS idx_app_components_page_id ON app_components (page_id);
CREATE INDEX IF NOT EXISTS idx_app_data_sources_app_id ON app_data_sources (app_id);
CREATE INDEX IF NOT EXISTS idx_saved_queries_org_id ON saved_queries (org_id);
CREATE INDEX IF NOT EXISTS idx_query_schedules_org_id ON query_schedules (org_id);
CREATE INDEX IF NOT EXISTS idx_eor_entities_org_id ON eor_entities (org_id);
CREATE INDEX IF NOT EXISTS idx_eor_employees_org_id ON eor_employees (org_id);
CREATE INDEX IF NOT EXISTS idx_eor_contracts_org_id ON eor_contracts (org_id);
CREATE INDEX IF NOT EXISTS idx_cor_contractors_org_id ON cor_contractors (org_id);
CREATE INDEX IF NOT EXISTS idx_cor_contracts_org_id ON cor_contracts (org_id);
CREATE INDEX IF NOT EXISTS idx_cor_payments_org_id ON cor_payments (org_id);
CREATE INDEX IF NOT EXISTS idx_global_benefit_plans_org_id ON global_benefit_plans (org_id);
CREATE INDEX IF NOT EXISTS idx_country_benefit_configs_org_id ON country_benefit_configs (org_id);
CREATE INDEX IF NOT EXISTS idx_global_benefit_enrollments_org_id ON global_benefit_enrollments (org_id);
CREATE INDEX IF NOT EXISTS idx_i9_documents_i9_form_id ON i9_documents (i9_form_id);
CREATE INDEX IF NOT EXISTS idx_peo_employee_enrollments_org_id ON peo_employee_enrollments (org_id);
CREATE INDEX IF NOT EXISTS idx_peo_workers_comp_codes_org_id ON peo_workers_comp_codes (org_id);
CREATE INDEX IF NOT EXISTS idx_peo_invoices_org_id ON peo_invoices (org_id);
CREATE INDEX IF NOT EXISTS idx_sandbox_access_log_sandbox_id ON sandbox_access_log (sandbox_id);
CREATE INDEX IF NOT EXISTS idx_chat_channel_members_channel_id ON chat_channel_members (channel_id);
CREATE INDEX IF NOT EXISTS idx_chat_reactions_message_id ON chat_reactions (message_id);
CREATE INDEX IF NOT EXISTS idx_workers_comp_policies_org_id ON workers_comp_policies (org_id);
CREATE INDEX IF NOT EXISTS idx_workers_comp_claims_org_id ON workers_comp_claims (org_id);
CREATE INDEX IF NOT EXISTS idx_workers_comp_class_codes_org_id ON workers_comp_class_codes (org_id);
CREATE INDEX IF NOT EXISTS idx_workers_comp_audits_org_id ON workers_comp_audits (org_id);
CREATE INDEX IF NOT EXISTS idx_dynamic_groups_org_id ON dynamic_groups (org_id);

-- ============================================================
-- Composite indexes for common multi-tenant query patterns
-- org_id + created_at DESC enables fast time-sorted org queries
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_goals_org_created ON goals (org_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reviews_org_created ON reviews (org_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_feedback_org_created ON feedback (org_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_leave_requests_org_created ON leave_requests (org_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_expense_reports_org_created ON expense_reports (org_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_it_requests_org_created ON it_requests (org_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_invoices_org_created ON invoices (org_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_job_postings_org_created ON job_postings (org_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_applications_org_created ON applications (org_id, applied_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_org_created ON notifications (org_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payroll_runs_org_created ON payroll_runs (org_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_devices_org_created ON devices (org_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_workflows_org_created ON workflows (org_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_travel_requests_org_created ON travel_requests (org_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_corporate_cards_org_created ON corporate_cards (org_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bill_payments_org_created ON bill_payments (org_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_chat_channels_org_created ON chat_channels (org_id, created_at DESC);

-- ============================================================
-- Employee-scoped composite indexes (for employee dashboards)
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_goals_employee ON goals (employee_id);
CREATE INDEX IF NOT EXISTS idx_reviews_employee ON reviews (employee_id);
CREATE INDEX IF NOT EXISTS idx_reviews_reviewer ON reviews (reviewer_id);
CREATE INDEX IF NOT EXISTS idx_salary_reviews_employee ON salary_reviews (employee_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_employee ON enrollments (employee_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_employee ON leave_requests (employee_id);
CREATE INDEX IF NOT EXISTS idx_benefit_enrollments_employee ON benefit_enrollments (employee_id);
CREATE INDEX IF NOT EXISTS idx_expense_reports_employee ON expense_reports (employee_id);
CREATE INDEX IF NOT EXISTS idx_payroll_entries_employee ON employee_payroll_entries (employee_id);
CREATE INDEX IF NOT EXISTS idx_time_entries_employee ON time_entries (employee_id);
CREATE INDEX IF NOT EXISTS idx_shifts_employee ON shifts (employee_id);
CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON notifications (recipient_id);
CREATE INDEX IF NOT EXISTS idx_emergency_contacts_employee ON emergency_contacts (employee_id);
CREATE INDEX IF NOT EXISTS idx_cobra_events_employee ON cobra_events (employee_id);
CREATE INDEX IF NOT EXISTS idx_flex_accounts_employee ON flex_benefit_accounts (employee_id);
CREATE INDEX IF NOT EXISTS idx_time_off_balances_employee ON time_off_balances (employee_id);
CREATE INDEX IF NOT EXISTS idx_certificates_employee ON certificates (employee_id);
CREATE INDEX IF NOT EXISTS idx_pip_employee ON performance_improvement_plans (employee_id);
CREATE INDEX IF NOT EXISTS idx_merit_recs_employee ON merit_recommendations (employee_id);
CREATE INDEX IF NOT EXISTS idx_offboarding_employee ON offboarding_processes (employee_id);
CREATE INDEX IF NOT EXISTS idx_tasks_assignee ON tasks (assignee_id);
CREATE INDEX IF NOT EXISTS idx_devices_assigned ON devices (assigned_to);
CREATE INDEX IF NOT EXISTS idx_it_requests_requester ON it_requests (requester_id);

-- ============================================================
-- Special indexes for high-traffic employee lookups
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_employees_org_email ON employees (org_id, email);
CREATE INDEX IF NOT EXISTS idx_employees_org_active ON employees (org_id, is_active);
CREATE INDEX IF NOT EXISTS idx_employees_org_dept ON employees (org_id, department_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_org_timestamp ON audit_log (org_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_recipient_read ON notifications (recipient_id, is_read);
CREATE INDEX IF NOT EXISTS idx_chat_messages_channel_created ON chat_messages (channel_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions (token);

-- Total single-column indexes: 205
-- Total composite indexes: 47
-- Grand total: 252
