import type { ModuleDoc } from '../../types'

const settings: ModuleDoc = {
  slug: 'settings',
  title: 'Settings',
  subtitle: 'Configure organization preferences, user accounts, security policies, SSO, and module access controls',
  icon: 'Settings',
  group: 'additional',
  lastUpdated: '2026-03-13',
  version: '1.0',

  overview: {
    description:
      'The Settings module is the central administration panel for your Tempo environment. It encompasses organization profile management, user account administration, security policies including SSO and MFA, module visibility toggles, notification preferences, branding customization, and data management controls. Settings are organized into logical sections so administrators can quickly find and update the configuration they need. Changes to critical settings require confirmation and are logged in the audit trail.',
    keyFeatures: [
      'Organization profile with company name, logo, timezone, and fiscal year configuration',
      'User account management with role assignment and deactivation',
      'SSO configuration for SAML 2.0, Google Workspace, and Azure AD',
      'Multi-factor authentication enforcement with TOTP and SMS options',
      'Module visibility toggles to enable or disable features per organization',
      'Notification channel configuration for email, Slack, and in-app alerts',
      'Custom branding with logo, colors, and login page customization',
      'Data retention policies and GDPR compliance controls',
    ],
    screenshotKey: 'settings/overview',
  },

  workflows: [
    {
      id: 'configure-org',
      title: 'Configuring Organization Settings',
      description:
        'Set up your organization\'s core profile including company information, timezone, fiscal year, and default currency.',
      estimatedTime: '5 minutes',
      roles: ['owner', 'admin'],
      steps: [
        {
          number: 1,
          title: 'Navigate to Settings',
          description:
            'Click "Settings" in the left sidebar. The Settings page opens to the Organization tab by default, showing your current company profile.',
          screenshotKey: 'settings/org-step-1',
        },
        {
          number: 2,
          title: 'Update company information',
          description:
            'Edit the company name, legal entity name, registration number, and primary address. These values appear on official documents, payslips, and compliance reports generated by Tempo.',
          screenshotKey: 'settings/org-step-2',
        },
        {
          number: 3,
          title: 'Set timezone and locale',
          description:
            'Select your organization\'s primary timezone and locale. The timezone affects date displays, notification schedules, and report generation times. The locale determines date format (MM/DD vs DD/MM), number formatting, and default language.',
          screenshotKey: 'settings/org-step-3',
          tip: 'For global organizations, individual users can override the timezone in their personal preferences while the org setting serves as the default.',
        },
        {
          number: 4,
          title: 'Configure fiscal year',
          description:
            'Set your fiscal year start month. This affects budget periods, headcount planning, and financial reports throughout Tempo. Common choices are January (calendar year) or April (UK/India fiscal year).',
          screenshotKey: 'settings/org-step-4',
        },
        {
          number: 5,
          title: 'Set default currency',
          description:
            'Choose the primary currency for payroll, expense reporting, and financial dashboards. Additional currencies can be enabled for multi-country operations with configurable exchange rates.',
          screenshotKey: 'settings/org-step-5',
        },
      ],
    },
    {
      id: 'setup-sso',
      title: 'Setting Up Single Sign-On (SSO)',
      description:
        'Configure SAML 2.0 or OIDC-based single sign-on so employees can log into Tempo using their corporate identity provider.',
      estimatedTime: '10 minutes',
      roles: ['owner', 'admin'],
      prerequisites: ['Access to your identity provider admin console (Google Workspace, Azure AD, Okta, etc.)'],
      steps: [
        {
          number: 1,
          title: 'Navigate to Security settings',
          description:
            'Go to Settings > Security > Single Sign-On. The SSO configuration panel shows the current status (Disabled, Configured, or Enforced) and the active provider.',
          screenshotKey: 'settings/sso-step-1',
        },
        {
          number: 2,
          title: 'Select your identity provider',
          description:
            'Choose from pre-configured providers (Google Workspace, Azure AD, Okta) or select "Custom SAML 2.0" for other providers. Pre-configured options auto-fill most settings, requiring only your tenant-specific values.',
          screenshotKey: 'settings/sso-step-2',
        },
        {
          number: 3,
          title: 'Enter provider details',
          description:
            'For SAML: enter the IdP Entity ID, SSO URL, and upload the signing certificate. For OIDC: enter the Client ID, Client Secret, Discovery URL, and authorized redirect URI. The Tempo SP metadata URL is displayed for you to register in your IdP.',
          screenshotKey: 'settings/sso-step-3',
          tip: 'Download the Tempo SP metadata XML and upload it directly to your IdP for the fastest configuration.',
        },
        {
          number: 4,
          title: 'Map user attributes',
          description:
            'Configure attribute mapping between your IdP and Tempo. Map the email, first name, last name, and department fields. Optionally map the job title and employee ID for automatic profile population.',
          screenshotKey: 'settings/sso-step-4',
        },
        {
          number: 5,
          title: 'Test the connection',
          description:
            'Click "Test SSO" to initiate a test authentication flow. You are redirected to your IdP login page. After successful authentication, the test panel shows the received attributes and any mapping issues.',
          screenshotKey: 'settings/sso-step-5',
        },
        {
          number: 6,
          title: 'Enable and optionally enforce SSO',
          description:
            'Click "Enable SSO" to allow SSO login alongside password login. To require all users to authenticate via SSO, toggle "Enforce SSO". When enforced, password login is disabled for all non-owner accounts. Owners always retain password access as a fallback.',
          screenshotKey: 'settings/sso-step-6',
        },
      ],
    },
    {
      id: 'manage-modules',
      title: 'Managing Module Visibility',
      description:
        'Enable or disable Tempo modules for your organization to customize which features are available in the sidebar and accessible to users.',
      estimatedTime: '3 minutes',
      roles: ['owner', 'admin'],
      steps: [
        {
          number: 1,
          title: 'Navigate to Module settings',
          description:
            'Go to Settings > Modules. A grid of all available Tempo modules is displayed, each with a toggle switch, description, and the number of active users.',
          screenshotKey: 'settings/modules-step-1',
        },
        {
          number: 2,
          title: 'Enable or disable modules',
          description:
            'Toggle any module on or off. Disabled modules are hidden from the sidebar, their pages become inaccessible, and their API endpoints return 403 errors. Data in disabled modules is preserved and becomes available again when re-enabled.',
          screenshotKey: 'settings/modules-step-2',
          tip: 'Disable modules your organization does not use to reduce sidebar clutter and simplify the user experience.',
        },
        {
          number: 3,
          title: 'Configure module access by group',
          description:
            'For modules that should be available only to specific teams, click the module card and select "Restrict to Groups". Choose one or more groups. Only members of the selected groups will see the module.',
          screenshotKey: 'settings/modules-step-3',
        },
        {
          number: 4,
          title: 'Save changes',
          description:
            'Click "Save Changes" at the bottom of the page. Module visibility updates take effect immediately. Users who are currently on a disabled module\'s page are redirected to the dashboard.',
          screenshotKey: 'settings/modules-step-4',
        },
      ],
    },
    {
      id: 'user-preferences',
      title: 'Configuring User Preferences',
      description:
        'Customize your personal Tempo experience including notification settings, display preferences, and accessibility options.',
      estimatedTime: '3 minutes',
      roles: ['owner', 'admin', 'hrbp', 'manager', 'employee'],
      steps: [
        {
          number: 1,
          title: 'Open personal preferences',
          description:
            'Click your avatar in the top-right corner and select "Preferences". Your personal settings panel opens with tabs for Profile, Notifications, Display, and Accessibility.',
          screenshotKey: 'settings/prefs-step-1',
        },
        {
          number: 2,
          title: 'Update notification preferences',
          description:
            'In the Notifications tab, configure which events trigger notifications and through which channels (in-app, email, Slack). Toggle categories like Leave, Payroll, Performance, and Chat. Set quiet hours during which email notifications are held.',
          screenshotKey: 'settings/prefs-step-2',
        },
        {
          number: 3,
          title: 'Set display preferences',
          description:
            'Choose your preferred theme (Light, Dark, or System), date format, time format (12h/24h), and default landing page. These settings apply only to your account and do not affect other users.',
          screenshotKey: 'settings/prefs-step-3',
          tip: 'The "System" theme option automatically switches between light and dark mode based on your operating system settings.',
        },
        {
          number: 4,
          title: 'Configure accessibility options',
          description:
            'Enable reduced motion to minimize animations, increase contrast mode for better readability, set a preferred font size, and enable screen reader optimization. These settings are designed to comply with WCAG 2.1 AA standards.',
          screenshotKey: 'settings/prefs-step-4',
        },
        {
          number: 5,
          title: 'Save preferences',
          description:
            'Click "Save Preferences". Changes take effect immediately. Your preferences are synced across devices, so logging in from a different computer preserves your settings.',
          screenshotKey: 'settings/prefs-step-5',
        },
      ],
    },
  ],

  faqs: [
    {
      question: 'What happens to data when I disable a module?',
      answer:
        'Disabling a module hides it from the interface and blocks API access, but all data is preserved. When you re-enable the module, all historical data, configurations, and records reappear exactly as they were. No data is deleted by toggling module visibility.',
    },
    {
      question: 'Can I have multiple SSO providers configured?',
      answer:
        'Yes. Tempo supports up to 3 concurrent SSO configurations. This is useful for organizations with multiple identity providers (e.g., Google Workspace for one subsidiary and Azure AD for another). Users are routed to the correct IdP based on their email domain.',
    },
    {
      question: 'How do I reset a user\'s password?',
      answer:
        'Navigate to Settings > Users, find the user, and click "Reset Password". The user receives an email with a secure link to set a new password. The link expires after 24 hours. If SSO is enforced, password reset is not available for non-owner accounts.',
    },
    {
      question: 'Can I customize the Tempo login page with our branding?',
      answer:
        'Yes. Go to Settings > Branding > Login Page. Upload your company logo, set a background image or color, add a welcome message, and customize the button colors. The branded login page applies to both password and SSO login flows.',
    },
    {
      question: 'How do I enforce MFA for all users?',
      answer:
        'Navigate to Settings > Security > Multi-Factor Authentication. Toggle "Require MFA" to on. Choose the allowed methods: authenticator app (TOTP), SMS, or both. Users are prompted to enroll on their next login. A 7-day grace period can be configured for enrollment.',
    },
    {
      question: 'Where can I find the audit log for setting changes?',
      answer:
        'Go to Settings > Audit Log. Every change to organization settings, user roles, security policies, and module configurations is logged with the timestamp, the user who made the change, the setting name, and the before/after values. Audit logs are retained for 7 years.',
    },
  ],

  tips: [
    'Review the Module Visibility settings when onboarding new departments to ensure they see only the modules relevant to their work.',
    'Set up SSO before inviting users to simplify their first login experience and eliminate the need for password management.',
    'Enable MFA enforcement for all admin and owner accounts at minimum, even if not required organization-wide.',
    'Use the "Test SSO" feature every time you update your IdP configuration to catch issues before they affect all users.',
    'Configure quiet hours in notification preferences to avoid email overload during non-working hours.',
    'Export the audit log quarterly for compliance documentation and internal security reviews.',
  ],

  relatedModules: ['groups', 'people', 'compliance', 'developer'],

  permissions: [
    {
      role: 'Owner',
      capabilities: [
        'Access and modify all organization settings',
        'Configure SSO, MFA, and security policies',
        'Enable or disable modules and set group-based access',
        'Manage user accounts, roles, and permissions',
        'View the full audit log',
        'Configure branding and login page customization',
      ],
    },
    {
      role: 'Admin',
      capabilities: [
        'Access and modify most organization settings',
        'Configure SSO and MFA (cannot disable owner MFA)',
        'Enable or disable modules and set group-based access',
        'Manage user accounts and roles (cannot modify owner accounts)',
        'View the audit log',
      ],
    },
    {
      role: 'HRBP',
      capabilities: [
        'View organization settings in read-only mode',
        'Manage user accounts for assigned departments',
        'View audit log entries for assigned scope',
      ],
    },
    {
      role: 'Manager',
      capabilities: [
        'Configure personal preferences and notification settings',
        'View team members\' basic account status',
      ],
    },
    {
      role: 'Employee',
      capabilities: [
        'Configure personal preferences, notifications, and display settings',
        'Update their own profile information',
        'Enroll in MFA and manage their own authentication methods',
      ],
    },
  ],
}

export default settings
