import { Sparkles } from 'lucide-react'
import { cn } from '@/lib/utils/cn'

interface AIBadgeProps {
  label?: string
  variant?: 'default' | 'subtle' | 'inline'
  className?: string
}

export function AIBadge({ label = 'AI', variant = 'default', className }: AIBadgeProps) {
  if (variant === 'subtle') {
    return (
      <span className={cn('inline-flex items-center text-tempo-500', className)} title="Generated by AI">
        <Sparkles size={12} />
      </span>
    )
  }

  if (variant === 'inline') {
    return (
      <span className={cn('inline-flex items-center gap-0.5 text-[0.6rem] text-tempo-600 font-medium', className)}>
        <Sparkles size={10} />
        {label}
      </span>
    )
  }

  return (
    <span className={cn(
      'inline-flex items-center gap-1 px-2 py-0.5 rounded-[var(--radius-pill)]',
      'bg-tempo-50 text-tempo-600 text-[0.6rem] font-medium border border-tempo-200',
      className
    )}>
      <Sparkles size={10} />
      {label}
    </span>
  )
}
